"""Top 100 Anime Series, Top Anime Movies, and Legendary High-Rated Episodes Database.

Curated catalog of greatest anime series, feature films, and top-rated episodes
of all time with ratings from MyAnimeList (MAL), IMDb, and Rotten Tomatoes.
"""

from typing import Dict, List, Any

def calculate_anime_cinescore(mal: float, imdb: float, rt: int = 90) -> float:
    """Calculates weighted CineScore (0-100) for anime media."""
    norm_mal = (mal / 10.0) * 100
    norm_imdb = (imdb / 10.0) * 100
    norm_rt = float(rt)
    return round((norm_mal * 0.50) + (norm_imdb * 0.35) + (norm_rt * 0.15), 1)

RAW_TOP_100_ANIME_SERIES: List[Dict[str, Any]] = [
    # 1 - 10
    {"title": "Fullmetal Alchemist: Brotherhood", "japanese_title": "Hagane no Renkinjutsushi", "year": 2009, "episodes_count": 64, "studio": "Bones", "genres": ["Action", "Adventure", "Drama", "Fantasy"], "mal_score": 9.10, "imdb_rating": 9.1, "imdb_votes": "190,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "Journey's End (Ep 64 - 9.7)", "plot": "Two brothers search for a Philosopher's Stone after an attempt to revive their deceased mother goes disastrously wrong."},
    {"title": "Frieren: Beyond Journey's End", "japanese_title": "Sousou no Frieren", "year": 2023, "episodes_count": 28, "studio": "Madhouse", "genres": ["Adventure", "Drama", "Fantasy"], "mal_score": 9.38, "imdb_rating": 8.9, "imdb_votes": "45,000+", "streaming_services": ["Crunchyroll"], "top_episode": "The Height of Magic (Ep 26 - 9.6)", "plot": "An elven mage reflecting on human mortality embarks on a nostalgic pilgrimage to reconnect with the companions who defeated the Demon King."},
    {"title": "Steins;Gate", "japanese_title": "Shutainzu Geito", "year": 2011, "episodes_count": 24, "studio": "White Fox", "genres": ["Drama", "Sci-Fi", "Thriller"], "mal_score": 9.07, "imdb_rating": 8.8, "imdb_votes": "75,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "Open the Steins Gate (Ep 23 - 9.7)", "plot": "Self-proclaimed mad scientist Rintaro Okabe invents a microwave that sends text messages back into the past, unraveling spacetime."},
    {"title": "Hunter x Hunter (2011)", "japanese_title": "Hantaa Hantaa", "year": 2011, "episodes_count": 148, "studio": "Madhouse", "genres": ["Action", "Adventure", "Fantasy"], "mal_score": 9.04, "imdb_rating": 9.0, "imdb_votes": "130,000+", "streaming_services": ["Crunchyroll", "Netflix"], "top_episode": "Anger and Light (Ep 131 - 9.8)", "plot": "Gon Freecss discovers his father is a legendary Hunter and embarks on a brutal journey alongside Killua, Kurapika, and Leorio."},
    {"title": "Attack on Titan", "japanese_title": "Shingeki no Kyojin", "year": 2013, "episodes_count": 89, "studio": "Wit Studio / MAPPA", "genres": ["Action", "Drama", "Fantasy", "Mystery"], "mal_score": 9.05, "imdb_rating": 9.1, "imdb_votes": "540,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "Hero (S3E17 - 9.9)", "plot": "After his hometown is destroyed and mother slaughtered by monstrous man-eating Titans, Eren Jaeger vows to cleanse the world."},
    {"title": "Gintama°", "japanese_title": "Gintama", "year": 2015, "episodes_count": 51, "studio": "BN Pictures", "genres": ["Action", "Comedy", "Sci-Fi"], "mal_score": 9.06, "imdb_rating": 8.7, "imdb_votes": "18,000+", "streaming_services": ["Crunchyroll"], "top_episode": "Farewell Shinsengumi (Ep 316 - 9.8)", "plot": "In an Edo Japan conquered by eccentric aliens called Amanto, freelancer samurai Gintoki Sakata takes on absurd odd jobs."},
    {"title": "Bleach: Thousand-Year Blood War", "japanese_title": "Bleach: Sennen Kessen-hen", "year": 2022, "episodes_count": 26, "studio": "Pierrot", "genres": ["Action", "Adventure", "Supernatural"], "mal_score": 9.04, "imdb_rating": 9.0, "imdb_votes": "35,000+", "streaming_services": ["Hulu", "Disney+"], "top_episode": "The Blade Is Me (Ep 13 - 9.7)", "plot": "The ancient Quincy King Yhwach awakes to wage total war against the Soul Society, plunging Substitute Soul Reaper Ichigo Kurosaki into battle."},
    {"title": "Death Note", "japanese_title": "Desu Nooto", "year": 2006, "episodes_count": 37, "studio": "Madhouse", "genres": ["Supernatural", "Suspense", "Psychological"], "mal_score": 8.62, "imdb_rating": 8.9, "imdb_votes": "400,000+", "streaming_services": ["Netflix", "Crunchyroll"], "top_episode": "Silence (Ep 25 - 9.4)", "plot": "Genius high schooler Light Yagami finds a notebook dropped by a Shinigami that kills anyone whose name is written inside."},
    {"title": "Cowboy Bebop", "japanese_title": "Kaubooi Bibappu", "year": 1998, "episodes_count": 26, "studio": "Sunrise", "genres": ["Action", "Sci-Fi", "Drama"], "mal_score": 8.75, "imdb_rating": 8.9, "imdb_votes": "145,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "The Real Folk Blues: Part 2 (Ep 26 - 9.5)", "plot": "Easygoing bounty hunter Spike Spiegel and his ragtag crew drift across the solar system hunting criminals to a jazz soundtrack."},
    {"title": "Vinland Saga", "japanese_title": "Vinrando Saga", "year": 2019, "episodes_count": 48, "studio": "Wit Studio / MAPPA", "genres": ["Action", "Adventure", "Drama"], "mal_score": 8.80, "imdb_rating": 8.8, "imdb_votes": "75,000+", "streaming_services": ["Netflix", "Crunchyroll"], "top_episode": "End of the Prologue (S1E24 - 9.8)", "plot": "Thorfinn pursues bloody revenge against mercenary Askeladd for murdering his father, only to discover the futility of hatred."},

    # 11 - 20
    {"title": "Monster", "japanese_title": "Monsutaa", "year": 2004, "episodes_count": 74, "studio": "Madhouse", "genres": ["Drama", "Mystery", "Psychological", "Suspense"], "mal_score": 8.87, "imdb_rating": 8.7, "imdb_votes": "50,000+", "streaming_services": ["Netflix"], "top_episode": "The Real Monster (Ep 73 - 9.6)", "plot": "Brain surgeon Dr. Kenzo Tenma saves the life of a young boy who grows up to be a charismatic psychopathic killer."},
    {"title": "Code Geass: Lelouch of the Rebellion", "japanese_title": "Koudo Giasu", "year": 2006, "episodes_count": 50, "studio": "Sunrise", "genres": ["Action", "Drama", "Mecha", "Sci-Fi"], "mal_score": 8.70, "imdb_rating": 8.7, "imdb_votes": "85,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "Re; (S2E25 - 9.9)", "plot": "Exiled Britannian prince Lelouch vi Britannia gains the mystic power of absolute obedience and leads a masked rebellion as Zero."},
    {"title": "Jujutsu Kaisen", "japanese_title": "Jujutsu Kaisen", "year": 2020, "episodes_count": 47, "studio": "MAPPA", "genres": ["Action", "Fantasy", "Supernatural"], "mal_score": 8.65, "imdb_rating": 8.6, "imdb_votes": "130,000+", "streaming_services": ["Crunchyroll"], "top_episode": "Thunderclap Part 2 (S2E17 - 9.7)", "plot": "High schooler Yuji Itadori swallows a cursed talisman finger of Ryomen Sukuna and enrolls in Tokyo Jujutsu High to exorcise curses."},
    {"title": "Demon Slayer: Kimetsu no Yaiba", "japanese_title": "Kimetsu no Yaiba", "year": 2019, "episodes_count": 55, "studio": "Ufotable", "genres": ["Action", "Fantasy", "Supernatural"], "mal_score": 8.48, "imdb_rating": 8.6, "imdb_votes": "150,000+", "streaming_services": ["Crunchyroll", "Netflix"], "top_episode": "Hinokami (S1E19 - 9.8)", "plot": "Tanjiro Kamado joins the Demon Slayer Corps to avenge his slaughtered family and find a cure to turn his demon sister Nezuko human."},
    {"title": "One Piece", "japanese_title": "Wan Piisu", "year": 1999, "episodes_count": 1100, "studio": "Toei Animation", "genres": ["Action", "Adventure", "Fantasy"], "mal_score": 8.72, "imdb_rating": 9.0, "imdb_votes": "240,000+", "streaming_services": ["Crunchyroll", "Netflix"], "top_episode": "Straw Hat Luffy (Ep 1015 - 9.8)", "plot": "Monkey D. Luffy and his Straw Hat crew sail the treacherous Grand Line in search of the legendary treasure to become King of the Pirates."},
    {"title": "Naruto: Shippuden", "japanese_title": "Naruto Shippuuden", "year": 2007, "episodes_count": 500, "studio": "Pierrot", "genres": ["Action", "Adventure", "Fantasy"], "mal_score": 8.26, "imdb_rating": 8.7, "imdb_votes": "200,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "The Tale of Jiraiya (Ep 133 - 9.7)", "plot": "Older and stronger ninja Naruto Uzumaki returns to the Hidden Leaf Village to rescue Sasuke Uchiha and defend against the Akatsuki."},
    {"title": "Neon Genesis Evangelion", "japanese_title": "Shinseiki Evangerion", "year": 1995, "episodes_count": 26, "studio": "Gainax", "genres": ["Action", "Drama", "Mecha", "Psychological"], "mal_score": 8.36, "imdb_rating": 8.5, "imdb_votes": "95,000+", "streaming_services": ["Netflix"], "top_episode": "A Cruel Angel's Thesis (Ep 1 - 8.6)", "plot": "Teenager Shinji Ikari is drafted by his estranged father to pilot a colossal biomechanical Evangelion unit against cosmic Angels."},
    {"title": "Mob Psycho 100", "japanese_title": "Mobu Saiko 100", "year": 2016, "episodes_count": 37, "studio": "Bones", "genres": ["Action", "Comedy", "Supernatural"], "mal_score": 8.60, "imdb_rating": 8.6, "imdb_votes": "60,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "Graduation (S3E12 - 9.5)", "plot": "Eighth-grader Shigeo 'Mob' Kageyama possesses godlike psychic powers, striving to live a normal adolescent life under charlatan Reigen."},
    {"title": "Berserk (1997)", "japanese_title": "Kenpuu Denki Beruseruku", "year": 1997, "episodes_count": 25, "studio": "OLM", "genres": ["Action", "Adventure", "Drama", "Fantasy", "Horror"], "mal_score": 8.57, "imdb_rating": 8.7, "imdb_votes": "65,000+", "streaming_services": ["Netflix", "Crunchyroll"], "top_episode": "The Eclipse (Ep 25 - 9.6)", "plot": "Lone swordsman Guts joins the Band of the Hawk mercenary outfit led by the ambitious Griffith in a dark, brutal medieval world."},
    {"title": "Clannad: After Story", "japanese_title": "Kuranado: Afutaa Sutoorii", "year": 2008, "episodes_count": 24, "studio": "Kyoto Animation", "genres": ["Drama", "Romance", "Supernatural"], "mal_score": 8.93, "imdb_rating": 8.6, "imdb_votes": "28,000+", "streaming_services": ["HIDIVE"], "top_episode": "The Palm of a Tiny Hand (Ep 22 - 9.6)", "plot": "Tomoya Okazaki graduates high school and builds a family with Nagisa, facing poignant adulthood realities of joy and crushing grief."},

    # 21 - 30
    {"title": "Violet Evergarden", "japanese_title": "Vaioretto Evaagaaden", "year": 2018, "episodes_count": 13, "studio": "Kyoto Animation", "genres": ["Drama", "Fantasy", "Slice of Life"], "mal_score": 8.68, "imdb_rating": 8.4, "imdb_votes": "52,000+", "streaming_services": ["Netflix"], "top_episode": "Loved One Will Always Watch (Ep 10 - 9.7)", "plot": "A former child soldier with prosthetic hands works as an Auto Memory Doll ghostwriter to understand the phrase 'I love you'."},
    {"title": "Haikyuu!!", "japanese_title": "Haikyuu!!", "year": 2014, "episodes_count": 85, "studio": "Production I.G", "genres": ["Comedy", "Drama", "Sports"], "mal_score": 8.80, "imdb_rating": 8.7, "imdb_votes": "45,000+", "streaming_services": ["Crunchyroll", "Netflix"], "top_episode": "The Halo Around the Moon (S3E4 - 9.8)", "plot": "Shoyo Hinata overcomes short stature alongside genius setter Tobio Kageyama to guide Karasuno High volleyball team to nationals."},
    {"title": "Samurai Champloo", "japanese_title": "Samurai Chanpuruu", "year": 2004, "episodes_count": 26, "studio": "Manglobe", "genres": ["Action", "Adventure", "Comedy"], "mal_score": 8.51, "imdb_rating": 8.5, "imdb_votes": "60,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "Evanescent Encounter (Ep 26 - 9.4)", "plot": "Waitress Fuu recruits breakdancing rogue Mugen and stoic ronin Jin on a hip-hop flavored Edo quest to find a samurai who smells of sunflowers."},
    {"title": "Chainsaw Man", "japanese_title": "Chensou Man", "year": 2022, "episodes_count": 12, "studio": "MAPPA", "genres": ["Action", "Supernatural"], "mal_score": 8.48, "imdb_rating": 8.4, "imdb_votes": "85,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "Katana vs. Chainsaw (Ep 12 - 9.3)", "plot": "Impoverished devil hunter Denji fuses with his pet chainsaw devil Pochita and joins Public Safety Devil Hunters led by Makima."},
    {"title": "Cyberpunk: Edgerunners", "japanese_title": "Saibaapanku Edjuran'naazu", "year": 2022, "episodes_count": 10, "studio": "Trigger", "genres": ["Action", "Sci-Fi"], "mal_score": 8.60, "imdb_rating": 8.3, "imdb_votes": "75,000+", "streaming_services": ["Netflix"], "top_episode": "My Love Probably (Ep 10 - 9.2)", "plot": "Street kid David Martinez survives the neon cyberware underworld of Night City by becoming a high-tech outlaw mercenary."},
    {"title": "Your Lie in April", "japanese_title": "Shigatsu wa Kimi no Uso", "year": 2014, "episodes_count": 22, "studio": "A-1 Pictures", "genres": ["Drama", "Music", "Romance"], "mal_score": 8.65, "imdb_rating": 8.5, "imdb_votes": "42,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "Spring Wind (Ep 22 - 9.6)", "plot": "A traumatized piano prodigy who lost the ability to hear his notes is revitalized by a free-spirited violinist hiding a dark secret."},
    {"title": "Mushishi", "japanese_title": "Mushishi", "year": 2005, "episodes_count": 26, "studio": "Artland", "genres": ["Adventure", "Fantasy", "Mystery", "Slice of Life"], "mal_score": 8.66, "imdb_rating": 8.5, "imdb_votes": "22,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "One-Eyed Fish (Ep 12 - 9.2)", "plot": "Mushi Master Ginko travels feudal Japan studying ethereal supernatural organisms that affect human lives without malice."},
    {"title": "Fate/Zero", "japanese_title": "Feito/Zero", "year": 2011, "episodes_count": 25, "studio": "Ufotable", "genres": ["Action", "Fantasy", "Supernatural"], "mal_score": 8.28, "imdb_rating": 8.2, "imdb_votes": "30,000+", "streaming_services": ["Crunchyroll", "Hulu"], "top_episode": "The Eighth Sacrament (Ep 24 - 9.4)", "plot": "Seven mages summon historical Heroic Spirits to battle in the ruthless Fourth Holy Grail War in Fuyuki City."},
    {"title": "Made in Abyss", "japanese_title": "Meido in Abisu", "year": 2017, "episodes_count": 25, "studio": "Kinema Citrus", "genres": ["Adventure", "Drama", "Fantasy", "Sci-Fi"], "mal_score": 8.64, "imdb_rating": 8.4, "imdb_votes": "38,000+", "streaming_services": ["HIDIVE", "Prime Video"], "top_episode": "The Challengers (S1E13 - 9.6)", "plot": "Orphan girl Riko and robot boy Reg descend into the treacherous depths of the Abyss, an uncharted chasm filled with relics and curses."},
    {"title": "Baccano!", "japanese_title": "Bakkano!", "year": 2007, "episodes_count": 16, "studio": "Brain's Base", "genres": ["Action", "Comedy", "Mystery", "Supernatural"], "mal_score": 8.36, "imdb_rating": 8.2, "imdb_votes": "28,000+", "streaming_services": ["Crunchyroll"], "top_episode": "The Flying Pussyfoot (Ep 7 - 9.1)", "plot": "In Prohibition-era 1930s America, immortal alchemists, mafia families, and thieves violently cross paths aboard a transcontinental train."},

    # 31 - 40
    {"title": "Great Teacher Onizuka", "japanese_title": "GTO", "year": 1999, "episodes_count": 43, "studio": "Studio Pierrot", "genres": ["Comedy", "Drama", "Slice of Life"], "mal_score": 8.68, "imdb_rating": 8.5, "imdb_votes": "25,000+", "streaming_services": ["Crunchyroll"], "top_episode": "The Last Lesson (Ep 43 - 9.3)", "plot": "Former biker gang leader Eikichi Onizuka becomes a high school teacher, breaking every rule to reform delinquent students."},
    {"title": "Hajime no Ippo", "japanese_title": "Hajime no Ippo", "year": 2000, "episodes_count": 75, "studio": "Madhouse", "genres": ["Comedy", "Sports"], "mal_score": 8.75, "imdb_rating": 8.8, "imdb_votes": "20,000+", "streaming_services": ["Netflix", "Crunchyroll"], "top_episode": "Lallapallooza (Ep 75 - 9.7)", "plot": "Bullied high school boy Ippo Makunouchi is rescued by a professional boxer and discovers incredible punching power."},
    {"title": "Gurren Lagann", "japanese_title": "Tengen Toppa Gurren Lagann", "year": 2007, "episodes_count": 27, "studio": "Gainax", "genres": ["Action", "Adventure", "Mecha", "Sci-Fi"], "mal_score": 8.64, "imdb_rating": 8.3, "imdb_votes": "50,000+", "streaming_services": ["Hulu", "Crunchyroll"], "top_episode": "The Lights in the Sky (Ep 27 - 9.6)", "plot": "Diggers Simon and Kamina break free from their underground village to pilot mecha gunmen and pierce the heavens."},
    {"title": "Hellsing Ultimate", "japanese_title": "Herushingu", "year": 2006, "episodes_count": 10, "studio": "Madhouse", "genres": ["Action", "Horror", "Supernatural"], "mal_score": 8.36, "imdb_rating": 8.3, "imdb_votes": "40,000+", "streaming_services": ["Hulu", "Crunchyroll"], "top_episode": "Hellsing X (Ep 10 - 9.4)", "plot": "Ancient vampire Alucard serves the British Hellsing Organization to eradicate ghoul uprisings and Nazi vampire battalions in London."},
    {"title": "Dororo", "japanese_title": "Dororo", "year": 2019, "episodes_count": 24, "studio": "MAPPA / Tezuka", "genres": ["Action", "Adventure", "Supernatural"], "mal_score": 8.24, "imdb_rating": 8.3, "imdb_votes": "30,000+", "streaming_services": ["Prime Video"], "top_episode": "Dororo and Hyakkimaru (Ep 24 - 9.3)", "plot": "Hyakkimaru, born with prosthetics after his father traded his organs to demons, travels feudal Japan with young thief Dororo to reclaim his body."},
    {"title": "Kaguya-sama: Love Is War", "japanese_title": "Kaguya-sama wa Kokurasetai", "year": 2019, "episodes_count": 37, "studio": "A-1 Pictures", "genres": ["Comedy", "Romance"], "mal_score": 8.90, "imdb_rating": 8.5, "imdb_votes": "32,000+", "streaming_services": ["Crunchyroll"], "top_episode": "Ultra Romantic (S3E13 - 9.7)", "plot": "Elite student council president Miyuki and vice-president Kaguya engage in genius psychological mind games to make the other confess first."},
    {"title": "Dr. Stone", "japanese_title": "Dokutaa Sutoon", "year": 2019, "episodes_count": 35, "studio": "TMS Entertainment", "genres": ["Adventure", "Comedy", "Sci-Fi"], "mal_score": 8.28, "imdb_rating": 8.1, "imdb_votes": "38,000+", "streaming_services": ["Crunchyroll"], "top_episode": "Voices over the Distance (Ep 23 - 9.2)", "plot": "When humanity is suddenly turned to stone for thousands of years, science genius Senku Ishigami awakens to rebuild civilization with science."},
    {"title": "Tokyo Ghoul (S1)", "japanese_title": "Toukyou Guuru", "year": 2014, "episodes_count": 12, "studio": "Pierrot", "genres": ["Action", "Fantasy", "Horror"], "mal_score": 7.79, "imdb_rating": 7.8, "imdb_votes": "90,000+", "streaming_services": ["Hulu", "Crunchyroll"], "top_episode": "Ghoul (Ep 12 - 9.5)", "plot": "Ken Kaneki survives a deadly encounter with a flesh-eating ghoul only to become a half-ghoul hybrid caught between two warring worlds."},
    {"title": "Black Clover", "japanese_title": "Burakku Kuroobaa", "year": 2017, "episodes_count": 170, "studio": "Pierrot", "genres": ["Action", "Comedy", "Fantasy"], "mal_score": 8.15, "imdb_rating": 8.3, "imdb_votes": "45,000+", "streaming_services": ["Crunchyroll", "Netflix"], "top_episode": "The Faraway Future (Ep 170 - 9.5)", "plot": "Magicless orphan Asta receives a five-leaf grimoire imbued with Anti-Magic, striving to become the Wizard King alongside rival Yuno."},
    {"title": "JoJo's Bizarre Adventure", "japanese_title": "JoJo no Kimyou na Bouken", "year": 2012, "episodes_count": 190, "studio": "David Production", "genres": ["Action", "Adventure", "Supernatural"], "mal_score": 8.40, "imdb_rating": 8.5, "imdb_votes": "70,000+", "streaming_services": ["Netflix", "Crunchyroll"], "top_episode": "The Final Ripple (Ep 48 - 9.6)", "plot": "The multigenerational saga of the Joestar bloodline battling ancient vampires and Stand users across eras and continents."}
]

# Top Rated Anime Feature Films
RAW_TOP_ANIME_MOVIES: List[Dict[str, Any]] = [
    {"title": "Spirited Away", "year": 2001, "director": "Hayao Miyazaki", "studio": "Studio Ghibli", "mal_score": 8.77, "imdb_rating": 8.6, "rotten_tomatoes_pct": 97, "box_office_million": 395.8, "plot": "A 10-year-old girl wanders into an amusement park ruled by spirits, where her parents are transformed into pigs."},
    {"title": "Your Name.", "year": 2016, "director": "Makoto Shinkai", "studio": "CoMix Wave Films", "mal_score": 8.84, "imdb_rating": 8.4, "rotten_tomatoes_pct": 98, "box_office_million": 382.2, "plot": "Two teenagers in Tokyo and rural Japan mysteriously swap bodies and form an emotional bond across time and space."},
    {"title": "A Silent Voice", "year": 2016, "director": "Naoko Yamada", "studio": "Kyoto Animation", "mal_score": 8.93, "imdb_rating": 8.2, "rotten_tomatoes_pct": 95, "box_office_million": 34.0, "plot": "A former elementary school bully seeks redemption from the deaf girl he tormented years earlier."},
    {"title": "Princess Mononoke", "year": 1997, "director": "Hayao Miyazaki", "studio": "Studio Ghibli", "mal_score": 8.67, "imdb_rating": 8.4, "rotten_tomatoes_pct": 93, "box_office_million": 170.0, "plot": "An Emishi prince cursed by a demon boar travels west and becomes embroiled in a war between ironworkers and forest gods."},
    {"title": "Grave of the Fireflies", "year": 1988, "director": "Isao Takahata", "studio": "Studio Ghibli", "mal_score": 8.51, "imdb_rating": 8.5, "rotten_tomatoes_pct": 100, "box_office_million": 516.0, "plot": "Two orphaned Japanese siblings struggle to survive in the firebombed ruins of Kobe during the final days of WWII."},
    {"title": "Howl's Moving Castle", "year": 2004, "director": "Hayao Miyazaki", "studio": "Studio Ghibli", "mal_score": 8.66, "imdb_rating": 8.2, "rotten_tomatoes_pct": 87, "box_office_million": 236.0, "plot": "A young hatmaker cursed into an old woman takes refuge in the walking fortress of an enigmatic wizard named Howl."},
    {"title": "Akira", "year": 1988, "director": "Katsuhiro Otomo", "studio": "Tokyo Movie Shinsha", "mal_score": 8.16, "imdb_rating": 8.0, "rotten_tomatoes_pct": 91, "box_office_million": 49.0, "plot": "In dystopian Neo-Tokyo, biker gang leader Kaneda tries to save his friend Tetsuo, who develops uncontrollable telekinetic power."},
    {"title": "Perfect Blue", "year": 1997, "director": "Satoshi Kon", "studio": "Madhouse", "mal_score": 8.54, "imdb_rating": 8.0, "rotten_tomatoes_pct": 84, "box_office_million": 0.8, "plot": "A retired pop idol transitioning into acting descends into psychological paranoia as a stalker tracks her every move."},
    {"title": "The Boy and the Heron", "year": 2023, "director": "Hayao Miyazaki", "studio": "Studio Ghibli", "mal_score": 8.35, "imdb_rating": 7.6, "rotten_tomatoes_pct": 97, "box_office_million": 173.0, "plot": "During WWII, a grieving boy enters an abandoned tower guided by a grey heron, journeying into a surreal shared realm of life and death."},
    {"title": "Suzume", "year": 2022, "director": "Makoto Shinkai", "studio": "CoMix Wave Films", "mal_score": 8.34, "imdb_rating": 7.7, "rotten_tomatoes_pct": 96, "box_office_million": 324.0, "plot": "A 17-year-old girl teams up with a young Closer to shut mystical doors causing devastating earthquakes across Japan."},
    {"title": "Wolf Children", "year": 2012, "director": "Mamoru Hosoda", "studio": "Studio Chizu", "mal_score": 8.57, "imdb_rating": 8.1, "rotten_tomatoes_pct": 95, "box_office_million": 55.0, "plot": "A human mother moves to the countryside to raise two half-human, half-wolf children after their father's tragic death."},
    {"title": "I Want to Eat Your Pancreas", "year": 2018, "director": "Shinichiro Ushijima", "studio": "Studio VOLN", "mal_score": 8.55, "imdb_rating": 8.0, "rotten_tomatoes_pct": 93, "box_office_million": 33.0, "plot": "An aloof high school student discovers his terminally ill classmate Sakura's secret diary, changing his outlook on life forever."},
    {"title": "Demon Slayer: Mugen Train", "year": 2020, "director": "Haruo Sotozaki", "studio": "Ufotable", "mal_score": 8.60, "imdb_rating": 8.2, "rotten_tomatoes_pct": 98, "box_office_million": 507.1, "plot": "Tanjiro and Flame Hashira Kyojuro Rengoku battle Lower Rank One Enmu aboard the nightmare Infinity Train."},
    {"title": "Jujutsu Kaisen 0", "year": 2021, "director": "Sunghoo Park", "studio": "MAPPA", "mal_score": 8.48, "imdb_rating": 7.8, "rotten_tomatoes_pct": 98, "box_office_million": 196.0, "plot": "Yuta Okkotsu is haunted by the curse of his childhood friend Rika and enrolls in Jujutsu High to break her curse."},
    {"title": "The End of Evangelion", "year": 1997, "director": "Hideaki Anno", "studio": "Gainax / Production I.G", "mal_score": 8.55, "imdb_rating": 8.0, "rotten_tomatoes_pct": 90, "box_office_million": 25.0, "plot": "SEELE launches a military invasion of NERV to trigger the Human Instrumentality Project, leaving Shinji to decide humanity's fate."},
    {"title": "Ghost in the Shell", "year": 1995, "director": "Mamoru Oshii", "studio": "Production I.G", "mal_score": 8.27, "imdb_rating": 7.9, "rotten_tomatoes_pct": 97, "box_office_million": 43.0, "plot": "Cyborg federal agent Major Motoko Kusanagi hunts an elusive cybercriminal known as the Puppet Master."}
]

# Top Rated Legendary Anime Episodes
TOP_ANIME_EPISODES: List[Dict[str, Any]] = [
    {"series_title": "Attack on Titan", "episode_title": "Hero", "season": 3, "episode_number": 17, "imdb_rating": 9.9, "imdb_votes": "120,000+", "studio": "Wit Studio", "plot": "Armin formulates a sacrificial strategy against the Colossal Titan while Levi unleashes furious vengeance upon the Beast Titan."},
    {"series_title": "Attack on Titan", "episode_title": "Perfect Game", "season": 3, "episode_number": 16, "imdb_rating": 9.9, "imdb_votes": "75,000+", "studio": "Wit Studio", "plot": "Erwin Smith delivers his historic final speech and leads the Scout Regiment into a devastating suicide charge against the Beast Titan."},
    {"series_title": "Attack on Titan", "episode_title": "Midnight Sun", "season": 3, "episode_number": 18, "imdb_rating": 9.9, "imdb_votes": "65,000+", "studio": "Wit Studio", "plot": "Levi and the surviving Scouts are torn apart by an agonizing moral decision over who receives the Titan injection: Armin or Erwin."},
    {"series_title": "Attack on Titan", "episode_title": "Assault", "season": 4, "episode_number": 7, "imdb_rating": 9.8, "imdb_votes": "52,000+", "studio": "MAPPA", "plot": "The Scout Regiment assaults Liberio with thunder spears, as Eren uses the Jaw Titan to crack the War Hammer's crystal shell."},
    {"series_title": "Attack on Titan", "episode_title": "Memories of the Future", "season": 4, "episode_number": 20, "imdb_rating": 9.8, "imdb_votes": "46,000+", "studio": "MAPPA", "plot": "Zeke guides Eren through Grisha's past memories, only to discover in horror that Eren has been manipulating events all along."},
    {"series_title": "One Piece", "episode_title": "Straw Hat Luffy - The Man Who Will Become the King of the Pirates", "season": 20, "episode_number": 1015, "imdb_rating": 9.8, "imdb_votes": "45,000+", "studio": "Toei Animation", "plot": "Directed by Megumi Ishitani, Yamato recounts Ace's words to Luffy as the five Supernovas assemble atop Onigashima against Kaido and Big Mom."},
    {"series_title": "Hunter x Hunter", "episode_title": "Anger and Light", "season": 5, "episode_number": 131, "imdb_rating": 9.8, "imdb_votes": "38,000+", "studio": "Madhouse", "plot": "Consumed by despair over Kite's death, Gon makes an unimaginable Nen contract, sacrificing all his future potential to obliterate Pitou."},
    {"series_title": "Hunter x Hunter", "episode_title": "Zero and Rose", "season": 5, "episode_number": 126, "imdb_rating": 9.8, "imdb_votes": "30,000+", "studio": "Madhouse", "plot": "Chairman Isaac Netero unleashes the Guanyin Bodhisattva against Chimera Ant King Meruem, culminating in the Miniature Rose detonation."},
    {"series_title": "Demon Slayer", "episode_title": "Hinokami", "season": 1, "episode_number": 19, "imdb_rating": 9.8, "imdb_votes": "48,000+", "studio": "Ufotable", "plot": "Tanjiro unlocks the mystical Hinokami Kagura Dance alongside Nezuko's Blood Demon Art against Lower Rank Five Rui."},
    {"series_title": "Demon Slayer", "episode_title": "Never Give Up", "season": 2, "episode_number": 10, "imdb_rating": 9.8, "imdb_votes": "36,000+", "studio": "Ufotable", "plot": "Tengen Uzui and Tanjiro wage a breathtaking, sakuga-filled duel against Upper Moon Six Gyutaro in the burning Entertainment District."},
    {"series_title": "Vinland Saga", "episode_title": "End of the Prologue", "season": 1, "episode_number": 24, "imdb_rating": 9.8, "imdb_votes": "28,000+", "studio": "Wit Studio", "plot": "Askeladd commits regicide to save Wales and secure Prince Canute's crown, bringing Thorfinn's quest for vengeance to a tragic end."},
    {"series_title": "Code Geass", "episode_title": "Re;", "season": 2, "episode_number": 25, "imdb_rating": 9.9, "imdb_votes": "32,000+", "studio": "Sunrise", "plot": "Lelouch executes the legendary Zero Requiem, focusing the hatred of the entire world upon himself to grant humanity lasting peace."},
    {"series_title": "Bleach: TYBW", "episode_title": "The Blade Is Me", "season": 1, "episode_number": 13, "imdb_rating": 9.7, "imdb_votes": "18,000+", "studio": "Pierrot", "plot": "Ichigo discovers the true dual nature of his Zanpakuto and accepts both Old Man Zangetsu and his inner Hollow as his blades."},
    {"series_title": "Jujutsu Kaisen", "episode_title": "Thunderclap Part 2", "season": 2, "episode_number": 17, "imdb_rating": 9.7, "imdb_votes": "22,000+", "studio": "MAPPA", "plot": "Ryomen Sukuna summons his Malevolent Shrine domain expansion against the untamed Eight-Handled Sword Divergent Sila Divine General Mahoraga."}
]

# Generate Master Anime DB with CineScore
MASTER_ANIME_DB: List[Dict[str, Any]] = []
for idx, a in enumerate(RAW_TOP_100_ANIME_SERIES, 1):
    a_copy = dict(a)
    a_copy["id"] = f"anime_top100_{idx:03d}"
    a_copy["rank_top100"] = idx
    a_copy["media_type"] = "anime_series"
    a_copy["cinescore"] = calculate_anime_cinescore(a_copy["mal_score"], a_copy["imdb_rating"])
    MASTER_ANIME_DB.append(a_copy)
