"""Top 100 Cartoon Series, Top 100 Animated Feature Films, and Top Cartoon Episodes Database.

Curated catalog of greatest Western animation, cartoons, and animated masterpieces
with ratings from IMDb, Rotten Tomatoes, and Letterboxd.
"""

from typing import Dict, List, Any

def calculate_cartoon_cinescore(imdb: float, rt: int, lb: float = 4.0) -> float:
    """Calculates weighted CineScore (0-100) for cartoon media."""
    norm_imdb = (imdb / 10.0) * 100
    norm_rt = float(rt)
    norm_lb = (lb / 5.0) * 100
    return round((norm_imdb * 0.45) + (norm_rt * 0.35) + (norm_lb * 0.20), 1)

RAW_TOP_CARTOON_SERIES: List[Dict[str, Any]] = [
    # 1 - 10
    {"title": "Avatar: The Last Airbender", "year": 2005, "creators": ["Michael Dante DiMartino", "Bryan Konietzko"], "genres": ["Animation", "Action", "Adventure", "Fantasy"], "seasons_count": 3, "episodes_count": 61, "imdb_rating": 9.3, "imdb_votes": "360,000+", "rotten_tomatoes_pct": 100, "streaming_services": ["Netflix", "Paramount+"], "top_episode": "Sozin's Comet: Part 4 (S3E21 - 9.9)", "plot": "Young Aang awakens from a century of frozen slumber to master all four elements and defeat the ruthless Fire Nation."},
    {"title": "Arcane", "year": 2021, "creators": ["Christian Linke", "Alex Yee"], "genres": ["Animation", "Action", "Adventure", "Sci-Fi"], "seasons_count": 2, "episodes_count": 18, "imdb_rating": 9.0, "imdb_votes": "300,000+", "rotten_tomatoes_pct": 100, "streaming_services": ["Netflix"], "top_episode": "The Monster You Created (S1E9 - 9.6)", "plot": "Two sisters battle on opposite sides of an escalating war between technological utopia Piltover and chemical underworld Zaun."},
    {"title": "Batman: The Animated Series", "year": 1992, "creators": ["Bob Kane", "Bruce Timm", "Paul Dini"], "genres": ["Animation", "Action", "Crime", "Mystery"], "seasons_count": 4, "episodes_count": 85, "imdb_rating": 9.0, "imdb_votes": "120,000+", "rotten_tomatoes_pct": 98, "streaming_services": ["Max", "Netflix"], "top_episode": "Heart of Ice (S1E14 - 9.4)", "plot": "The Dark Knight protects Gotham City from eccentric rogues including Joker, Freeze, and Two-Face with noir art-deco elegance."},
    {"title": "Rick and Morty", "year": 2013, "creators": ["Dan Harmon", "Justin Roiland"], "genres": ["Animation", "Adventure", "Comedy", "Sci-Fi"], "seasons_count": 7, "episodes_count": 71, "imdb_rating": 9.1, "imdb_votes": "610,000+", "rotten_tomatoes_pct": 90, "streaming_services": ["Max", "Hulu"], "top_episode": "The Ricklantis Mixup (S3E7 - 9.8)", "plot": "An alcoholic sociopathic genius scientist drags his timid grandson on insane dimensional misadventures across the multiverse."},
    {"title": "BoJack Horseman", "year": 2014, "creators": ["Raphael Bob-Waksberg"], "genres": ["Animation", "Comedy", "Drama"], "seasons_count": 6, "episodes_count": 77, "imdb_rating": 8.8, "imdb_votes": "190,000+", "rotten_tomatoes_pct": 93, "streaming_services": ["Netflix"], "top_episode": "The View from Halfway Down (S6E15 - 9.9)", "plot": "A cynical, washed-up humanoid 90s sitcom horse searches for meaning amidst addiction and existential guilt in Hollywood."},
    {"title": "Gravity Falls", "year": 2012, "creators": ["Alex Hirsch"], "genres": ["Animation", "Adventure", "Comedy", "Mystery"], "seasons_count": 2, "episodes_count": 40, "imdb_rating": 8.9, "imdb_votes": "140,000+", "rotten_tomatoes_pct": 100, "streaming_services": ["Disney+", "Hulu"], "top_episode": "Not What He Seems (S2E11 - 9.8)", "plot": "Twins Dipper and Mabel Pines spend the summer with Grunkle Stan in Gravity Falls, uncovering a journal of occult phenomena."},
    {"title": "Over the Garden Wall", "year": 2014, "creators": ["Patrick McHale"], "genres": ["Animation", "Adventure", "Drama", "Fantasy"], "seasons_count": 1, "episodes_count": 10, "imdb_rating": 8.8, "imdb_votes": "78,000+", "rotten_tomatoes_pct": 92, "streaming_services": ["Hulu", "Max"], "top_episode": "The Unknown (S1E10 - 9.5)", "plot": "Two half-brothers wander lost through the mysterious, atmospheric autumn woods of the Unknown, hunted by the Beast."},
    {"title": "Samurai Jack", "year": 2001, "creators": ["Genndy Tartakovsky"], "genres": ["Animation", "Action", "Adventure", "Sci-Fi"], "seasons_count": 5, "episodes_count": 62, "imdb_rating": 8.5, "imdb_votes": "65,000+", "rotten_tomatoes_pct": 96, "streaming_services": ["Max"], "top_episode": "Jack and the Traveling Creatures (S3E6 - 9.3)", "plot": "A noble Japanese samurai prince is cast into a dystopian future ruled by the shapeshifting demon master Aku."},
    {"title": "Spider-Man: The Animated Series", "year": 1994, "creators": ["Stan Lee", "John Semper"], "genres": ["Animation", "Action", "Adventure", "Sci-Fi"], "seasons_count": 5, "episodes_count": 65, "imdb_rating": 8.4, "imdb_votes": "52,000+", "rotten_tomatoes_pct": 90, "streaming_services": ["Disney+"], "top_episode": "Spider Wars: Chapter 2 (S5E13 - 9.1)", "plot": "Peter Parker balances collegiate studies and photography while swinging across Manhattan as the heroic web-slinging Spider-Man."},
    {"title": "X-Men '97", "year": 2024, "creators": ["Beau DeMayo"], "genres": ["Animation", "Action", "Adventure", "Sci-Fi"], "seasons_count": 1, "episodes_count": 10, "imdb_rating": 8.9, "imdb_votes": "60,000+", "rotten_tomatoes_pct": 99, "streaming_services": ["Disney+"], "top_episode": "Remember It (S1E5 - 9.8)", "plot": "A band of heroic mutants face dangerous new trials following the loss of Professor X in an unforgiving world."},

    # 11 - 20
    {"title": "Star Wars: The Clone Wars", "year": 2008, "creators": ["George Lucas"], "genres": ["Animation", "Action", "Adventure", "Sci-Fi"], "seasons_count": 7, "episodes_count": 133, "imdb_rating": 8.4, "imdb_votes": "120,000+", "rotten_tomatoes_pct": 93, "streaming_services": ["Disney+"], "top_episode": "Victory and Death (S7E12 - 9.9)", "plot": "Jedi Knights Anakin Skywalker and Obi-Wan Kenobi guide clone troopers and Padawan Ahsoka Tano through the galactic Clone Wars."},
    {"title": "Justice League Unlimited", "year": 2004, "creators": ["Bruce Timm"], "genres": ["Animation", "Action", "Adventure", "Sci-Fi"], "seasons_count": 3, "episodes_count": 39, "imdb_rating": 8.7, "imdb_votes": "40,000+", "rotten_tomatoes_pct": 95, "streaming_services": ["Max"], "top_episode": "Epilogue (S2E13 - 9.4)", "plot": "An expanded league of dozens of superheroes defends Earth against cosmic conquerors, Cadmus conspiracies, and Darkseid."},
    {"title": "Adventure Time", "year": 2010, "creators": ["Pendleton Ward"], "genres": ["Animation", "Action", "Adventure", "Comedy"], "seasons_count": 10, "episodes_count": 283, "imdb_rating": 8.6, "imdb_votes": "120,000+", "rotten_tomatoes_pct": 100, "streaming_services": ["Max", "Hulu"], "top_episode": "Come Along with Me (S10E13 - 9.7)", "plot": "Finn the Human and magical shape-shifting dog Jake explore the post-apocalyptic, enchanted Land of Ooo."},
    {"title": "Regular Show", "year": 2010, "creators": ["J.G. Quintel"], "genres": ["Animation", "Adventure", "Comedy", "Fantasy"], "seasons_count": 8, "episodes_count": 261, "imdb_rating": 8.5, "imdb_votes": "75,000+", "rotten_tomatoes_pct": 92, "streaming_services": ["Hulu", "Max"], "top_episode": "A Regular Epic Final Battle (S8E28 - 9.8)", "plot": "Blue jay Mordecai and raccoon Rigby work as park groundskeepers, turning mundane chores into supernatural cosmic disasters."},
    {"title": "Primal", "year": 2019, "creators": ["Genndy Tartakovsky"], "genres": ["Animation", "Action", "Adventure", "Fantasy"], "seasons_count": 2, "episodes_count": 20, "imdb_rating": 8.7, "imdb_votes": "55,000+", "rotten_tomatoes_pct": 100, "streaming_services": ["Max"], "top_episode": "Plague of Madness (S1E7 - 9.5)", "plot": "A caveman and a tyrannosaurus bond over tragic bereavement, forging an alliance to survive a merciless prehistoric world."},
    {"title": "South Park", "year": 1997, "creators": ["Trey Parker", "Matt Stone"], "genres": ["Animation", "Comedy"], "seasons_count": 26, "episodes_count": 325, "imdb_rating": 8.7, "imdb_votes": "400,000+", "rotten_tomatoes_pct": 80, "streaming_services": ["Max", "Paramount+"], "top_episode": "Scott Tenorman Must Die (S5E4 - 9.6)", "plot": "Four irreverent Colorado boys embark on biting, boundary-pushing satirical adventures mocking modern society."},
    {"title": "The Simpsons (Golden Era)", "year": 1989, "creators": ["Matt Groening"], "genres": ["Animation", "Comedy"], "seasons_count": 35, "episodes_count": 760, "imdb_rating": 8.7, "imdb_votes": "430,000+", "rotten_tomatoes_pct": 85, "streaming_services": ["Disney+"], "top_episode": "Homer's Enemy (S8E23 - 9.3)", "plot": "The timeless comic exploits of Homer, Marge, Bart, Lisa, and Maggie Simpson living in eccentric Springfield."},
    {"title": "Futurama", "year": 1999, "creators": ["Matt Groening", "David X. Cohen"], "genres": ["Animation", "Adventure", "Comedy", "Sci-Fi"], "seasons_count": 8, "episodes_count": 150, "imdb_rating": 8.5, "imdb_votes": "260,000+", "rotten_tomatoes_pct": 86, "streaming_services": ["Hulu", "Disney+"], "top_episode": "Jurassic Bark (S4E7 - 9.3)", "plot": "Unwittingly cryogenically preserved for a thousand years, 20th-century slacker Fry awakens to join Planet Express in 3000 AD."},
    {"title": "Invincible", "year": 2021, "creators": ["Robert Kirkman"], "genres": ["Animation", "Action", "Adventure", "Drama"], "seasons_count": 2, "episodes_count": 16, "imdb_rating": 8.7, "imdb_votes": "230,000+", "rotten_tomatoes_pct": 99, "streaming_services": ["Prime Video"], "top_episode": "Where I Really Come From (S1E8 - 9.7)", "plot": "Teenager Mark Grayson discovers the violent, terrifying reality of his alien father Omni-Man's imperialist legacy."},
    {"title": "Young Justice", "year": 2010, "creators": ["Brandon Vietti", "Greg Weisman"], "genres": ["Animation", "Action", "Adventure", "Sci-Fi"], "seasons_count": 4, "episodes_count": 98, "imdb_rating": 8.6, "imdb_votes": "50,000+", "rotten_tomatoes_pct": 95, "streaming_services": ["Max"], "top_episode": "Endgame (S2E20 - 9.3)", "plot": "Teen superhero proteges form an undercover covert operations unit to tackle global black-ops missions."}
]

# Top 100 Animated Feature Films
RAW_TOP_ANIMATED_MOVIES: List[Dict[str, Any]] = [
    # 1 - 10
    {"title": "The Lion King", "year": 1994, "studio": "Walt Disney Pictures", "director": "Roger Allers, Rob Minkoff", "imdb_rating": 8.5, "rotten_tomatoes_pct": 93, "box_office_million": 968.5, "oscar_wins": 2, "plot": "Lion cub prince Simba flees the Pride Lands following his father's death, returning as an adult to reclaim his kingdom."},
    {"title": "Spider-Man: Into the Spider-Verse", "year": 2018, "studio": "Sony Pictures Animation", "director": "Bob Persichetti, Peter Ramsey", "imdb_rating": 8.4, "rotten_tomatoes_pct": 97, "box_office_million": 384.3, "oscar_wins": 1, "plot": "Brooklyn teen Miles Morales gains spider-powers and unites with alternate dimension Spider-Heroes to foil Kingpin."},
    {"title": "Spider-Man: Across the Spider-Verse", "year": 2023, "studio": "Sony Pictures Animation", "director": "Joaquim Dos Santos, Kemp Powers", "imdb_rating": 8.6, "rotten_tomatoes_pct": 95, "box_office_million": 690.9, "oscar_wins": 0, "plot": "Miles Morales catapults across the multiverse where he clashes with the Spider-Society over saving his father."},
    {"title": "Toy Story", "year": 1995, "studio": "Pixar Animation Studios", "director": "John Lasseter", "imdb_rating": 8.3, "rotten_tomatoes_pct": 100, "box_office_million": 373.0, "oscar_wins": 1, "plot": "Cowboy doll Woody feels threatened when flashy modern spaceman action figure Buzz Lightyear joins Andy's toy bedroom."},
    {"title": "Toy Story 3", "year": 2010, "studio": "Pixar Animation Studios", "director": "Lee Unkrich", "imdb_rating": 8.3, "rotten_tomatoes_pct": 98, "box_office_million": 1067.0, "oscar_wins": 2, "plot": "As owner Andy heads off to college, Woody and Buzz are mistakenly donated to Sunnyside Daycare ruled by tyrant bear Lotso."},
    {"title": "WALL-E", "year": 2008, "studio": "Pixar Animation Studios", "director": "Andrew Stanton", "imdb_rating": 8.4, "rotten_tomatoes_pct": 95, "box_office_million": 521.3, "oscar_wins": 1, "plot": "A lonely trash-compacting robot left on a desolate Earth falls in love with sleek probe EVE and journeys into deep space."},
    {"title": "Ratatouille", "year": 2007, "studio": "Pixar Animation Studios", "director": "Brad Bird", "imdb_rating": 8.1, "rotten_tomatoes_pct": 96, "box_office_million": 623.7, "oscar_wins": 1, "plot": "A rat with extraordinary culinary taste forms an alliance with a clumsy garbage boy in a prestigious Paris restaurant."},
    {"title": "Up", "year": 2009, "studio": "Pixar Animation Studios", "director": "Pete Docter, Bob Peterson", "imdb_rating": 8.3, "rotten_tomatoes_pct": 98, "box_office_million": 735.1, "oscar_wins": 2, "plot": "Widower Carl Fredricksen ties thousands of balloons to his house to fly to South America, accompanied by wilderness explorer Russell."},
    {"title": "Finding Nemo", "year": 2003, "studio": "Pixar Animation Studios", "director": "Andrew Stanton", "imdb_rating": 8.2, "rotten_tomatoes_pct": 99, "box_office_million": 940.3, "oscar_wins": 1, "plot": "Anxious clownfish father Marlin braves the vast ocean alongside forgetful Dory to rescue his captured son in Sydney Harbour."},
    {"title": "The Incredibles", "year": 2004, "studio": "Pixar Animation Studios", "director": "Brad Bird", "imdb_rating": 8.0, "rotten_tomatoes_pct": 97, "box_office_million": 631.6, "oscar_wins": 2, "plot": "A family of undercover superheroes living quiet suburban lives is forced into battle to stop megalomaniac supervillain Syndrome."},

    # 11 - 20
    {"title": "Monsters, Inc.", "year": 2001, "studio": "Pixar Animation Studios", "director": "Pete Docter", "imdb_rating": 8.1, "rotten_tomatoes_pct": 96, "box_office_million": 577.4, "oscar_wins": 1, "plot": "Top scarer Sulley and one-eyed Mike Wazowski discover that human child laughter generates far more energy than screams."},
    {"title": "Coco", "year": 2017, "studio": "Pixar Animation Studios", "director": "Lee Unkrich, Adrian Molina", "imdb_rating": 8.4, "rotten_tomatoes_pct": 97, "box_office_million": 807.8, "oscar_wins": 2, "plot": "Aspiring musician Miguel enters the vibrant Land of the Dead on Día de los Muertos to unlock his ancestral family legacy."},
    {"title": "Inside Out", "year": 2015, "studio": "Pixar Animation Studios", "director": "Pete Docter, Ronnie del Carmen", "imdb_rating": 8.1, "rotten_tomatoes_pct": 98, "box_office_million": 858.8, "oscar_wins": 1, "plot": "Emotions Joy, Sadness, Anger, Fear, and Disgust struggle to guide 11-year-old Riley through an unsettling move to San Francisco."},
    {"title": "Inside Out 2", "year": 2024, "studio": "Pixar Animation Studios", "director": "Kelsey Mann", "imdb_rating": 7.7, "rotten_tomatoes_pct": 90, "box_office_million": 1690.0, "oscar_wins": 0, "plot": "Teenager Riley enters puberty, welcoming chaotic new headquarters emotions led by Anxiety, Envy, and Ennui."},
    {"title": "Soul", "year": 2020, "studio": "Pixar Animation Studios", "director": "Pete Docter, Kemp Powers", "imdb_rating": 8.0, "rotten_tomatoes_pct": 95, "box_office_million": 121.9, "oscar_wins": 2, "plot": "Middle school band teacher Joe Gardner falls down a manhole into the Great Before, mentoring uninspired soul 22 on what makes life worthwhile."},
    {"title": "Shrek", "year": 2001, "studio": "DreamWorks Animation", "director": "Andrew Adamson, Vicky Jenson", "imdb_rating": 7.9, "rotten_tomatoes_pct": 88, "box_office_million": 487.9, "oscar_wins": 1, "plot": "An antisocial ogre agrees to rescue Princess Fiona from a fire-breathing dragon to regain his beloved swamp from Lord Farquaad."},
    {"title": "Shrek 2", "year": 2004, "studio": "DreamWorks Animation", "director": "Andrew Adamson, Kelly Asbury", "imdb_rating": 7.3, "rotten_tomatoes_pct": 89, "box_office_million": 928.7, "oscar_wins": 0, "plot": "Shrek and Fiona travel to the kingdom of Far Far Away to meet her royal parents, confronting Fairy Godmother and Puss in Boots."},
    {"title": "How to Train Your Dragon", "year": 2010, "studio": "DreamWorks Animation", "director": "Dean DeBlois, Chris Sanders", "imdb_rating": 8.1, "rotten_tomatoes_pct": 99, "box_office_million": 494.9, "oscar_wins": 0, "plot": "Misfit Viking teen Hiccup secretly befriends an injured Night Fury dragon named Toothless, proving dragons are not beasts."},
    {"title": "Beauty and the Beast", "year": 1991, "studio": "Walt Disney Pictures", "director": "Gary Trousdale, Kirk Wise", "imdb_rating": 8.0, "rotten_tomatoes_pct": 93, "box_office_million": 425.0, "oscar_wins": 2, "plot": "Book-loving Belle offers herself as prisoner in an enchanted castle to save her father, looking past the monstrous Beast's exterior."},
    {"title": "Aladdin", "year": 1992, "studio": "Walt Disney Pictures", "director": "Ron Clements, John Musker", "imdb_rating": 8.0, "rotten_tomatoes_pct": 95, "box_office_million": 504.1, "oscar_wins": 2, "plot": "Street urchin Aladdin finds a magical lamp housing an exuberant Genie who grants three wishes to win Princess Jasmine's heart."}
]

# Top Rated Cartoon Episodes
TOP_CARTOON_EPISODES: List[Dict[str, Any]] = [
    {"series_title": "Avatar: The Last Airbender", "episode_title": "Sozin's Comet, Part 4: Avatar Aang", "season": 3, "episode_number": 21, "imdb_rating": 9.9, "imdb_votes": "22,000+", "director": "Joaquim Dos Santos", "plot": "Aang takes away Fire Lord Ozai's bending in a transcendent finale, while Zuko and Katara duel Azula in the Agni Kai."},
    {"series_title": "Avatar: The Last Airbender", "episode_title": "The Crossroads of Destiny", "season": 2, "episode_number": 20, "imdb_rating": 9.6, "imdb_votes": "15,000+", "director": "Michael Dante DiMartino", "plot": "In the crystal catacombs beneath Ba Sing Se, Zuko chooses his sister Azula, striking Aang with lightning."},
    {"series_title": "Arcane", "episode_title": "The Monster You Created", "season": 1, "episode_number": 9, "imdb_rating": 9.6, "imdb_votes": "40,000+", "director": "Pascal Charrue, Arnaud Delord", "plot": "Jinx hosts a horrific tea party with Vi and Caitlyn, concluding with a rocket launched at the Piltover Council."},
    {"series_title": "Star Wars: The Clone Wars", "episode_title": "Victory and Death", "season": 7, "episode_number": 12, "imdb_rating": 9.9, "imdb_votes": "30,000+", "director": "Nathaniel Villanueva", "plot": "Ahsoka and Rex survive the crash of their Venator Star Destroyer as Order 66 obliterates the Jedi Order."},
    {"series_title": "Star Wars: The Clone Wars", "episode_title": "The Phantom Apprentice", "season": 7, "episode_number": 10, "imdb_rating": 9.9, "imdb_votes": "25,000+", "director": "Nathaniel Villanueva", "plot": "Ahsoka engages in a breathtaking, motion-captured lightsaber duel against Darth Maul in the throne room of Mandalore."},
    {"series_title": "Gravity Falls", "episode_title": "Not What He Seems", "season": 2, "episode_number": 11, "imdb_rating": 9.8, "imdb_votes": "18,000+", "director": "Stephen Sandoval", "plot": "The countdown to the interdimensional portal finishes, revealing the true author of the journals: Stan's twin brother Ford."},
    {"series_title": "X-Men '97", "episode_title": "Remember It", "season": 1, "episode_number": 5, "imdb_rating": 9.8, "imdb_votes": "24,000+", "director": "Emi Yonemura", "plot": "A surprise Tri-Sentinel attack decimates the mutant nation of Genosha in an emotionally shattering battle."},
    {"series_title": "Rick and Morty", "episode_title": "The Ricklantis Mixup", "season": 3, "episode_number": 7, "imdb_rating": 9.8, "imdb_votes": "65,000+", "director": "Dominic Polcino", "plot": "Explores the dystopian class struggles within the Citadel of Ricks, culminating in the chilling election of Evil Morty."},
    {"series_title": "BoJack Horseman", "episode_title": "The View from Halfway Down", "season": 6, "episode_number": 15, "imdb_rating": 9.9, "imdb_votes": "35,000+", "director": "Amy Winfrey", "plot": "BoJack reflects on life, regret, and the finality of death in a surreal dream sequence."},
    {"series_title": "Batman: The Animated Series", "episode_title": "Heart of Ice", "season": 1, "episode_number": 14, "imdb_rating": 9.4, "imdb_votes": "12,000+", "director": "Bruce Timm", "plot": "The Emmy-winning tragedy of Victor Fries, driven by love to save his terminally ill cryogenic wife Nora as Mr. Freeze."}
]

# Generate Master Cartoons DB with CineScore
MASTER_CARTOONS_DB: List[Dict[str, Any]] = []
for idx, c in enumerate(RAW_TOP_CARTOON_SERIES, 1):
    c_copy = dict(c)
    c_copy["id"] = f"cartoon_top100_{idx:03d}"
    c_copy["rank_top100"] = idx
    c_copy["media_type"] = "cartoon_series"
    c_copy["cinescore"] = calculate_cartoon_cinescore(c_copy["imdb_rating"], c_copy["rotten_tomatoes_pct"])
    MASTER_CARTOONS_DB.append(c_copy)
