"""Curated Master Cinema Catalog & Top 100 Greatest Movies of All Time.

Contains multi-source ratings (IMDb, Rotten Tomatoes, Metacritic, Letterboxd),
box office metrics, director metadata, and streaming platforms.
"""

from typing import Dict, List, Any

def calculate_cinescore(imdb: float, rt: int, meta: int, lb: float) -> float:
    """Calculates normalized CineScore (0 - 100) weighted across 4 major critical sources."""
    norm_imdb = (imdb / 10.0) * 100
    norm_rt = float(rt)
    norm_meta = float(meta)
    norm_lb = (lb / 5.0) * 100
    score = (norm_imdb * 0.35) + (norm_rt * 0.30) + (norm_meta * 0.20) + (norm_lb * 0.15)
    return round(score, 1)

# Complete 100 Masterpieces
RAW_TOP_100: List[Dict[str, Any]] = [
    # 1 - 10
    {"title": "The Shawshank Redemption", "year": 1994, "director": "Frank Darabont", "genres": ["Drama", "Crime"], "cast": ["Tim Robbins", "Morgan Freeman", "Bob Gunton"], "runtime_mins": 142, "imdb_rating": 9.3, "imdb_votes": "2,900,000+", "rotten_tomatoes_pct": 91, "metacritic_score": 82, "letterboxd_rating": 4.5, "oscar_wins": 0, "box_office_million": 73.3, "streaming_services": ["HBO Max", "Netflix"], "plot": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency."},
    {"title": "The Godfather", "year": 1972, "director": "Francis Ford Coppola", "genres": ["Crime", "Drama"], "cast": ["Marlon Brando", "Al Pacino", "James Caan"], "runtime_mins": 175, "imdb_rating": 9.2, "imdb_votes": "2,050,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 100, "letterboxd_rating": 4.6, "oscar_wins": 3, "box_office_million": 250.3, "streaming_services": ["Paramount+", "HBO Max"], "plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son."},
    {"title": "The Dark Knight", "year": 2008, "director": "Christopher Nolan", "genres": ["Action", "Crime", "Drama"], "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"], "runtime_mins": 152, "imdb_rating": 9.0, "imdb_votes": "2,850,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 84, "letterboxd_rating": 4.5, "oscar_wins": 2, "box_office_million": 1009.0, "streaming_services": ["HBO Max", "Netflix"], "plot": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests."},
    {"title": "The Godfather Part II", "year": 1974, "director": "Francis Ford Coppola", "genres": ["Crime", "Drama"], "cast": ["Al Pacino", "Robert De Niro", "Robert Duvall"], "runtime_mins": 202, "imdb_rating": 9.0, "imdb_votes": "1,380,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 90, "letterboxd_rating": 4.5, "oscar_wins": 6, "box_office_million": 93.0, "streaming_services": ["Paramount+", "HBO Max"], "plot": "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands the family syndicate."},
    {"title": "12 Angry Men", "year": 1957, "director": "Sidney Lumet", "genres": ["Crime", "Drama"], "cast": ["Henry Fonda", "Lee J. Cobb", "Martin Balsam"], "runtime_mins": 96, "imdb_rating": 9.0, "imdb_votes": "860,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 97, "letterboxd_rating": 4.6, "oscar_wins": 0, "box_office_million": 2.0, "streaming_services": ["Prime Video", "Apple TV"], "plot": "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence."},
    {"title": "Schindler's List", "year": 1993, "director": "Steven Spielberg", "genres": ["Biography", "Drama", "History"], "cast": ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"], "runtime_mins": 195, "imdb_rating": 9.0, "imdb_votes": "1,450,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 95, "letterboxd_rating": 4.5, "oscar_wins": 7, "box_office_million": 322.2, "streaming_services": ["Netflix", "Apple TV"], "plot": "In German-occupied Poland during WWII, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce."},
    {"title": "The Lord of the Rings: The Return of the King", "year": 2003, "director": "Peter Jackson", "genres": ["Action", "Adventure", "Drama", "Fantasy"], "cast": ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"], "runtime_mins": 201, "imdb_rating": 9.0, "imdb_votes": "1,980,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 94, "letterboxd_rating": 4.6, "oscar_wins": 11, "box_office_million": 1146.0, "streaming_services": ["HBO Max", "Prime Video"], "plot": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom."},
    {"title": "Pulp Fiction", "year": 1994, "director": "Quentin Tarantino", "genres": ["Crime", "Drama"], "cast": ["John Travolta", "Uma Thurman", "Samuel L. Jackson"], "runtime_mins": 154, "imdb_rating": 8.9, "imdb_votes": "2,200,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 95, "letterboxd_rating": 4.4, "oscar_wins": 1, "box_office_million": 213.9, "streaming_services": ["HBO Max", "Netflix"], "plot": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence."},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "year": 2001, "director": "Peter Jackson", "genres": ["Action", "Adventure", "Drama", "Fantasy"], "cast": ["Elijah Wood", "Ian McKellen", "Orlando Bloom"], "runtime_mins": 178, "imdb_rating": 8.9, "imdb_votes": "2,020,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 92, "letterboxd_rating": 4.5, "oscar_wins": 4, "box_office_million": 898.2, "streaming_services": ["HBO Max", "Prime Video"], "plot": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth."},
    {"title": "The Good, the Bad and the Ugly", "year": 1966, "director": "Sergio Leone", "genres": ["Western", "Adventure"], "cast": ["Clint Eastwood", "Eli Wallach", "Lee Van Cleef"], "runtime_mins": 178, "imdb_rating": 8.8, "imdb_votes": "810,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 90, "letterboxd_rating": 4.4, "oscar_wins": 0, "box_office_million": 25.1, "streaming_services": ["HBO Max", "Prime Video"], "plot": "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery."},

    # 11 - 20
    {"title": "Forrest Gump", "year": 1994, "director": "Robert Zemeckis", "genres": ["Drama", "Romance"], "cast": ["Tom Hanks", "Robin Wright", "Gary Sinise"], "runtime_mins": 142, "imdb_rating": 8.8, "imdb_votes": "2,250,000+", "rotten_tomatoes_pct": 71, "metacritic_score": 82, "letterboxd_rating": 4.1, "oscar_wins": 6, "box_office_million": 678.2, "streaming_services": ["Paramount+", "Netflix"], "plot": "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75."},
    {"title": "Fight Club", "year": 1999, "director": "David Fincher", "genres": ["Drama", "Thriller"], "cast": ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"], "runtime_mins": 139, "imdb_rating": 8.8, "imdb_votes": "2,300,000+", "rotten_tomatoes_pct": 79, "metacritic_score": 67, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 101.2, "streaming_services": ["Disney+", "Hulu"], "plot": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more."},
    {"title": "The Lord of the Rings: The Two Towers", "year": 2002, "director": "Peter Jackson", "genres": ["Action", "Adventure", "Fantasy"], "cast": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"], "runtime_mins": 179, "imdb_rating": 8.8, "imdb_votes": "1,800,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 87, "letterboxd_rating": 4.5, "oscar_wins": 2, "box_office_million": 947.9, "streaming_services": ["HBO Max", "Prime Video"], "plot": "While Frodo and Sam edge closer to Mordor with the help of Gollum, the divided fellowship makes a stand against Sauron's new ally."},
    {"title": "Inception", "year": 2010, "director": "Christopher Nolan", "genres": ["Action", "Sci-Fi", "Adventure"], "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"], "runtime_mins": 148, "imdb_rating": 8.8, "imdb_votes": "2,550,000+", "rotten_tomatoes_pct": 87, "metacritic_score": 74, "letterboxd_rating": 4.3, "oscar_wins": 4, "box_office_million": 839.0, "streaming_services": ["HBO Max", "Netflix"], "plot": "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO."},
    {"title": "Star Wars: Episode V - The Empire Strikes Back", "year": 1980, "director": "Irvin Kershner", "genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"], "cast": ["Mark Hamill", "Harrison Ford", "Carrie Fisher"], "runtime_mins": 124, "imdb_rating": 8.7, "imdb_votes": "1,380,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 82, "letterboxd_rating": 4.4, "oscar_wins": 1, "box_office_million": 538.4, "streaming_services": ["Disney+"], "plot": "After the Rebels are brutally overpowered by the Empire, Luke Skywalker begins Jedi training with Yoda while his friends are pursued by Darth Vader."},
    {"title": "The Matrix", "year": 1999, "director": "Lana Wachowski, Lilly Wachowski", "genres": ["Action", "Sci-Fi"], "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"], "runtime_mins": 136, "imdb_rating": 8.7, "imdb_votes": "2,050,000+", "rotten_tomatoes_pct": 83, "metacritic_score": 73, "letterboxd_rating": 4.3, "oscar_wins": 4, "box_office_million": 467.2, "streaming_services": ["HBO Max", "Prime Video"], "plot": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers."},
    {"title": "Goodfellas", "year": 1990, "director": "Martin Scorsese", "genres": ["Biography", "Crime", "Drama"], "cast": ["Robert De Niro", "Ray Liotta", "Joe Pesci"], "runtime_mins": 145, "imdb_rating": 8.7, "imdb_votes": "1,260,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 92, "letterboxd_rating": 4.5, "oscar_wins": 1, "box_office_million": 47.1, "streaming_services": ["HBO Max", "Netflix"], "plot": "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy and Tommy."},
    {"title": "One Flew Over the Cuckoo's Nest", "year": 1975, "director": "Milos Forman", "genres": ["Drama"], "cast": ["Jack Nicholson", "Louise Fletcher", "Michael Berryman"], "runtime_mins": 133, "imdb_rating": 8.7, "imdb_votes": "1,090,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 84, "letterboxd_rating": 4.4, "oscar_wins": 5, "box_office_million": 109.0, "streaming_services": ["HBO Max", "Prime Video"], "plot": "In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution where he rallies other patients."},
    {"title": "Interstellar", "year": 2014, "director": "Christopher Nolan", "genres": ["Sci-Fi", "Adventure", "Drama"], "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"], "runtime_mins": 169, "imdb_rating": 8.7, "imdb_votes": "2,100,000+", "rotten_tomatoes_pct": 73, "metacritic_score": 74, "letterboxd_rating": 4.4, "oscar_wins": 1, "box_office_million": 731.0, "streaming_services": ["Paramount+", "HBO Max"], "plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."},
    {"title": "Seven Samurai", "year": 1954, "director": "Akira Kurosawa", "genres": ["Action", "Drama"], "cast": ["Toshirô Mifune", "Takashi Shimura", "Keiko Tsushima"], "runtime_mins": 207, "imdb_rating": 8.6, "imdb_votes": "365,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 98, "letterboxd_rating": 4.6, "oscar_wins": 0, "box_office_million": 3.5, "streaming_services": ["Criterion Channel", "HBO Max"], "plot": "Farmers from a village exploited by bandits hire a veteran samurai for protection, who gathers six other samurai to join him."},

    # 21 - 30
    {"title": "Se7en", "year": 1995, "director": "David Fincher", "genres": ["Crime", "Drama", "Mystery"], "cast": ["Morgan Freeman", "Brad Pitt", "Kevin Spacey"], "runtime_mins": 127, "imdb_rating": 8.6, "imdb_votes": "1,820,000+", "rotten_tomatoes_pct": 83, "metacritic_score": 65, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 327.3, "streaming_services": ["HBO Max", "Netflix"], "plot": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives."},
    {"title": "The Silence of the Lambs", "year": 1991, "director": "Jonathan Demme", "genres": ["Crime", "Drama", "Thriller"], "cast": ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney"], "runtime_mins": 118, "imdb_rating": 8.6, "imdb_votes": "1,550,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 86, "letterboxd_rating": 4.4, "oscar_wins": 5, "box_office_million": 272.7, "streaming_services": ["HBO Max", "Prime Video"], "plot": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer."},
    {"title": "Saving Private Ryan", "year": 1998, "director": "Steven Spielberg", "genres": ["Drama", "War"], "cast": ["Tom Hanks", "Matt Damon", "Tom Sizemore"], "runtime_mins": 169, "imdb_rating": 8.6, "imdb_votes": "1,510,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 91, "letterboxd_rating": 4.3, "oscar_wins": 5, "box_office_million": 482.3, "streaming_services": ["Paramount+", "Netflix"], "plot": "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action."},
    {"title": "City of God", "year": 2002, "director": "Fernando Meirelles, Kátia Lund", "genres": ["Crime", "Drama"], "cast": ["Alexandre Rodrigues", "Leandro Firmino", "Matheus Nachtergaele"], "runtime_mins": 130, "imdb_rating": 8.6, "imdb_votes": "810,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 79, "letterboxd_rating": 4.5, "oscar_wins": 0, "box_office_million": 30.6, "streaming_services": ["HBO Max", "Paramount+"], "plot": "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin."},
    {"title": "Life Is Beautiful", "year": 1997, "director": "Roberto Benigni", "genres": ["Comedy", "Drama", "Romance"], "cast": ["Roberto Benigni", "Nicoletta Braschi", "Giorgio Cantarini"], "runtime_mins": 116, "imdb_rating": 8.6, "imdb_votes": "740,000+", "rotten_tomatoes_pct": 80, "metacritic_score": 59, "letterboxd_rating": 4.3, "oscar_wins": 3, "box_office_million": 230.1, "streaming_services": ["Prime Video", "Apple TV"], "plot": "When an open-minded Jewish waiter and his son are sent to a concentration camp, he uses a perfect mixture of will, humor, and imagination."},
    {"title": "The Green Mile", "year": 1999, "director": "Frank Darabont", "genres": ["Crime", "Drama", "Fantasy"], "cast": ["Tom Hanks", "Michael Clarke Duncan", "David Morse"], "runtime_mins": 189, "imdb_rating": 8.6, "imdb_votes": "1,400,000+", "rotten_tomatoes_pct": 79, "metacritic_score": 61, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 286.8, "streaming_services": ["HBO Max", "Netflix"], "plot": "A tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments."},
    {"title": "Spirited Away", "year": 2001, "director": "Hayao Miyazaki", "genres": ["Animation", "Adventure", "Fantasy"], "cast": ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"], "runtime_mins": 125, "imdb_rating": 8.6, "imdb_votes": "850,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 96, "letterboxd_rating": 4.5, "oscar_wins": 1, "box_office_million": 395.8, "streaming_services": ["HBO Max", "Netflix"], "plot": "A 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts."},
    {"title": "Parasite", "year": 2019, "director": "Bong Joon-ho", "genres": ["Drama", "Thriller", "Comedy"], "cast": ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"], "runtime_mins": 132, "imdb_rating": 8.5, "imdb_votes": "950,000+", "rotten_tomatoes_pct": 99, "metacritic_score": 96, "letterboxd_rating": 4.6, "oscar_wins": 4, "box_office_million": 263.1, "streaming_services": ["HBO Max", "Hulu"], "plot": "Greed and class discrimination threaten the relationship between the wealthy Park family and the destitute Kim clan."},
    {"title": "Léon: The Professional", "year": 1994, "director": "Luc Besson", "genres": ["Action", "Crime", "Drama"], "cast": ["Jean Reno", "Gary Oldman", "Natalie Portman"], "runtime_mins": 110, "imdb_rating": 8.5, "imdb_votes": "1,240,000+", "rotten_tomatoes_pct": 74, "metacritic_score": 64, "letterboxd_rating": 4.1, "oscar_wins": 0, "box_office_million": 45.3, "streaming_services": ["Netflix", "Prime Video"], "plot": "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered by corrupt DEA agents."},
    {"title": "The Prestige", "year": 2006, "director": "Christopher Nolan", "genres": ["Drama", "Mystery", "Sci-Fi"], "cast": ["Christian Bale", "Hugh Jackman", "Scarlett Johansson"], "runtime_mins": 130, "imdb_rating": 8.5, "imdb_votes": "1,450,000+", "rotten_tomatoes_pct": 77, "metacritic_score": 66, "letterboxd_rating": 4.2, "oscar_wins": 0, "box_office_million": 109.7, "streaming_services": ["Apple TV", "Prime Video"], "plot": "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything."},

    # 31 - 40
    {"title": "The Lion King", "year": 1994, "director": "Roger Allers, Rob Minkoff", "genres": ["Animation", "Adventure", "Drama"], "cast": ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"], "runtime_mins": 88, "imdb_rating": 8.5, "imdb_votes": "1,150,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 88, "letterboxd_rating": 4.3, "oscar_wins": 2, "box_office_million": 968.5, "streaming_services": ["Disney+"], "plot": "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself."},
    {"title": "The Usual Suspects", "year": 1995, "director": "Bryan Singer", "genres": ["Crime", "Drama", "Mystery"], "cast": ["Kevin Spacey", "Gabriel Byrne", "Chazz Palminteri"], "runtime_mins": 106, "imdb_rating": 8.5, "imdb_votes": "1,150,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 77, "letterboxd_rating": 4.2, "oscar_wins": 2, "box_office_million": 34.4, "streaming_services": ["Prime Video", "Apple TV"], "plot": "The sole survivor of a pier shoot-out tells the police the story of how five criminals met in a police lineup and were manipulated by Keyser Söze."},
    {"title": "Whiplash", "year": 2014, "director": "Damien Chazelle", "genres": ["Drama", "Music"], "cast": ["Miles Teller", "J.K. Simmons", "Paul Reiser"], "runtime_mins": 106, "imdb_rating": 8.5, "imdb_votes": "980,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 89, "letterboxd_rating": 4.4, "oscar_wins": 3, "box_office_million": 49.0, "streaming_services": ["Netflix", "Prime Video"], "plot": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an unyielding instructor."},
    {"title": "Gladiator", "year": 2000, "director": "Ridley Scott", "genres": ["Action", "Adventure", "Drama"], "cast": ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"], "runtime_mins": 155, "imdb_rating": 8.5, "imdb_votes": "1,620,000+", "rotten_tomatoes_pct": 80, "metacritic_score": 67, "letterboxd_rating": 4.2, "oscar_wins": 5, "box_office_million": 503.2, "streaming_services": ["Paramount+", "Netflix"], "plot": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery."},
    {"title": "The Departed", "year": 2006, "director": "Martin Scorsese", "genres": ["Crime", "Drama", "Thriller"], "cast": ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"], "runtime_mins": 151, "imdb_rating": 8.5, "imdb_votes": "1,440,000+", "rotten_tomatoes_pct": 91, "metacritic_score": 85, "letterboxd_rating": 4.3, "oscar_wins": 4, "box_office_million": 291.5, "streaming_services": ["HBO Max", "Netflix"], "plot": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston."},
    {"title": "Apocalypse Now", "year": 1979, "director": "Francis Ford Coppola", "genres": ["Drama", "Mystery", "War"], "cast": ["Martin Sheen", "Marlon Brando", "Robert Duvall"], "runtime_mins": 147, "imdb_rating": 8.4, "imdb_votes": "710,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 94, "letterboxd_rating": 4.4, "oscar_wins": 2, "box_office_million": 105.0, "streaming_services": ["HBO Max", "Apple TV"], "plot": "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god."},
    {"title": "Alien", "year": 1979, "director": "Ridley Scott", "genres": ["Horror", "Sci-Fi"], "cast": ["Sigourney Weaver", "Tom Skerritt", "John Hurt"], "runtime_mins": 117, "imdb_rating": 8.5, "imdb_votes": "950,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 89, "letterboxd_rating": 4.3, "oscar_wins": 1, "box_office_million": 184.7, "streaming_services": ["Hulu", "Disney+"], "plot": "The crew of a commercial spacecraft encounters a deadly lifeform after investigating an unknown transmission."},
    {"title": "Psycho", "year": 1960, "director": "Alfred Hitchcock", "genres": ["Horror", "Mystery", "Thriller"], "cast": ["Anthony Perkins", "Janet Leigh", "Vera Miles"], "runtime_mins": 109, "imdb_rating": 8.5, "imdb_votes": "720,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 97, "letterboxd_rating": 4.4, "oscar_wins": 0, "box_office_million": 50.0, "streaming_services": ["Peacock", "Apple TV"], "plot": "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother."},
    {"title": "Rear Window", "year": 1954, "director": "Alfred Hitchcock", "genres": ["Mystery", "Thriller"], "cast": ["James Stewart", "Grace Kelly", "Wendell Corey"], "runtime_mins": 112, "imdb_rating": 8.5, "imdb_votes": "520,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 100, "letterboxd_rating": 4.4, "oscar_wins": 0, "box_office_million": 36.8, "streaming_services": ["Criterion Channel", "Apple TV"], "plot": "A wheelchair-bound photographer spies on his neighbors from his Greenwich Village courtyard window and becomes convinced one of them has committed murder."},
    {"title": "Casablanca", "year": 1942, "director": "Michael Curtiz", "genres": ["Drama", "Romance", "War"], "cast": ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid"], "runtime_mins": 102, "imdb_rating": 8.5, "imdb_votes": "600,000+", "rotten_tomatoes_pct": 99, "metacritic_score": 100, "letterboxd_rating": 4.4, "oscar_wins": 3, "box_office_million": 4.2, "streaming_services": ["HBO Max", "Criterion Channel"], "plot": "A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco."},

    # 41 - 50
    {"title": "Cinema Paradiso", "year": 1988, "director": "Giuseppe Tornatore", "genres": ["Drama", "Romance"], "cast": ["Philippe Noiret", "Enzo Cannavale", "Antonella Attili"], "runtime_mins": 155, "imdb_rating": 8.5, "imdb_votes": "285,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 80, "letterboxd_rating": 4.5, "oscar_wins": 1, "box_office_million": 13.0, "streaming_services": ["HBO Max", "Apple TV"], "plot": "A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the projectionist."},
    {"title": "Memento", "year": 2000, "director": "Christopher Nolan", "genres": ["Mystery", "Thriller"], "cast": ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"], "runtime_mins": 113, "imdb_rating": 8.4, "imdb_votes": "1,320,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 83, "letterboxd_rating": 4.2, "oscar_wins": 0, "box_office_million": 40.0, "streaming_services": ["Prime Video", "Apple TV"], "plot": "A man with short-term memory loss attempts to track down his wife's murderer using notes and tattoos."},
    {"title": "Spider-Man: Across the Spider-Verse", "year": 2023, "director": "Joaquim Dos Santos", "genres": ["Animation", "Action", "Adventure"], "cast": ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"], "runtime_mins": 140, "imdb_rating": 8.6, "imdb_votes": "380,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 86, "letterboxd_rating": 4.5, "oscar_wins": 0, "box_office_million": 690.9, "streaming_services": ["Netflix", "Apple TV"], "plot": "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence."},
    {"title": "Dune: Part Two", "year": 2024, "director": "Denis Villeneuve", "genres": ["Sci-Fi", "Action", "Adventure"], "cast": ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"], "runtime_mins": 166, "imdb_rating": 8.6, "imdb_votes": "520,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 79, "letterboxd_rating": 4.5, "oscar_wins": 0, "box_office_million": 714.4, "streaming_services": ["HBO Max", "Apple TV"], "plot": "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family."},
    {"title": "Oppenheimer", "year": 2023, "director": "Christopher Nolan", "genres": ["Biography", "Drama", "History"], "cast": ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr."], "runtime_mins": 180, "imdb_rating": 8.8, "imdb_votes": "780,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 90, "letterboxd_rating": 4.5, "oscar_wins": 7, "box_office_million": 977.0, "streaming_services": ["Peacock", "Prime Video"], "plot": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb."},
    {"title": "Django Unchained", "year": 2012, "director": "Quentin Tarantino", "genres": ["Drama", "Western"], "cast": ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"], "runtime_mins": 165, "imdb_rating": 8.5, "imdb_votes": "1,700,000+", "rotten_tomatoes_pct": 87, "metacritic_score": 81, "letterboxd_rating": 4.2, "oscar_wins": 2, "box_office_million": 425.4, "streaming_services": ["Netflix", "Paramount+"], "plot": "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner."},
    {"title": "The Shining", "year": 1980, "director": "Stanley Kubrick", "genres": ["Drama", "Horror"], "cast": ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd"], "runtime_mins": 146, "imdb_rating": 8.4, "imdb_votes": "1,120,000+", "rotten_tomatoes_pct": 83, "metacritic_score": 68, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 47.3, "streaming_services": ["HBO Max", "Prime Video"], "plot": "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence."},
    {"title": "WALL-E", "year": 2008, "director": "Andrew Stanton", "genres": ["Animation", "Adventure", "Family", "Sci-Fi"], "cast": ["Ben Burtt", "Elissa Knight", "Jeff Garlin"], "runtime_mins": 98, "imdb_rating": 8.4, "imdb_votes": "1,200,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 95, "letterboxd_rating": 4.3, "oscar_wins": 1, "box_office_million": 521.3, "streaming_services": ["Disney+"], "plot": "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."},
    {"title": "Amélie", "year": 2001, "director": "Jean-Pierre Jeunet", "genres": ["Comedy", "Romance"], "cast": ["Audrey Tautou", "Mathieu Kassovitz", "Rufus"], "runtime_mins": 122, "imdb_rating": 8.3, "imdb_votes": "780,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 69, "letterboxd_rating": 4.2, "oscar_wins": 0, "box_office_million": 174.2, "streaming_services": ["Prime Video", "Apple TV"], "plot": "Amélie is an innocent and naive girl in Paris with her own sense of justice who decides to help those around her."},
    {"title": "Avengers: Infinity War", "year": 2018, "director": "Anthony Russo, Joe Russo", "genres": ["Action", "Adventure", "Sci-Fi"], "cast": ["Robert Downey Jr.", "Chris Hemsworth", "Josh Brolin"], "runtime_mins": 149, "imdb_rating": 8.4, "imdb_votes": "1,200,000+", "rotten_tomatoes_pct": 85, "metacritic_score": 68, "letterboxd_rating": 4.0, "oscar_wins": 0, "box_office_million": 2052.4, "streaming_services": ["Disney+"], "plot": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation."},

    # 51 - 60
    {"title": "Avengers: Endgame", "year": 2019, "director": "Anthony Russo, Joe Russo", "genres": ["Action", "Adventure", "Drama", "Sci-Fi"], "cast": ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"], "runtime_mins": 181, "imdb_rating": 8.4, "imdb_votes": "1,300,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 78, "letterboxd_rating": 3.9, "oscar_wins": 0, "box_office_million": 2799.4, "streaming_services": ["Disney+"], "plot": "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more."},
    {"title": "Coco", "year": 2017, "director": "Lee Unkrich, Adrian Molina", "genres": ["Animation", "Adventure", "Family", "Music"], "cast": ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt"], "runtime_mins": 105, "imdb_rating": 8.4, "imdb_votes": "580,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 81, "letterboxd_rating": 4.2, "oscar_wins": 2, "box_office_million": 814.3, "streaming_services": ["Disney+"], "plot": "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather."},
    {"title": "Your Name.", "year": 2016, "director": "Makoto Shinkai", "genres": ["Animation", "Drama", "Fantasy", "Romance"], "cast": ["Ryûnosuke Kamiki", "Mone Kamishiraishi", "Ryô Narita"], "runtime_mins": 106, "imdb_rating": 8.4, "imdb_votes": "330,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 79, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 382.2, "streaming_services": ["Crunchyroll", "Prime Video"], "plot": "Two teenagers share a profound, magical connection upon discovering they are swapping bodies."},
    {"title": "Joker", "year": 2019, "director": "Todd Phillips", "genres": ["Crime", "Drama", "Thriller"], "cast": ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"], "runtime_mins": 122, "imdb_rating": 8.4, "imdb_votes": "1,480,000+", "rotten_tomatoes_pct": 69, "metacritic_score": 59, "letterboxd_rating": 3.8, "oscar_wins": 2, "box_office_million": 1074.4, "streaming_services": ["HBO Max", "Netflix"], "plot": "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain."},
    {"title": "Braveheart", "year": 1995, "director": "Mel Gibson", "genres": ["Biography", "Drama", "History", "War"], "cast": ["Mel Gibson", "Sophie Marceau", "Patrick McGoohan"], "runtime_mins": 178, "imdb_rating": 8.3, "imdb_votes": "1,080,000+", "rotten_tomatoes_pct": 76, "metacritic_score": 68, "letterboxd_rating": 3.9, "oscar_wins": 5, "box_office_million": 213.2, "streaming_services": ["Paramount+", "Prime Video"], "plot": "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England."},
    {"title": "Taxi Driver", "year": 1976, "director": "Martin Scorsese", "genres": ["Crime", "Drama"], "cast": ["Robert De Niro", "Jodie Foster", "Cybill Shepherd"], "runtime_mins": 114, "imdb_rating": 8.2, "imdb_votes": "930,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 94, "letterboxd_rating": 4.2, "oscar_wins": 0, "box_office_million": 28.3, "streaming_services": ["HBO Max", "Apple TV"], "plot": "A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence fuels his urge for violent action."},
    {"title": "2001: A Space Odyssey", "year": 1968, "director": "Stanley Kubrick", "genres": ["Adventure", "Sci-Fi"], "cast": ["Keir Dullea", "Gary Lockwood", "William Sylvester"], "runtime_mins": 149, "imdb_rating": 8.3, "imdb_votes": "730,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 84, "letterboxd_rating": 4.3, "oscar_wins": 1, "box_office_million": 74.0, "streaming_services": ["HBO Max", "Criterion Channel"], "plot": "After uncovering a mysterious artifact buried beneath the Lunar surface, a spacecraft is sent to Jupiter with HAL 9000."},
    {"title": "Oldboy", "year": 2003, "director": "Park Chan-wook", "genres": ["Action", "Drama", "Mystery"], "cast": ["Choi Min-sik", "Yoo Ji-tae", "Kang Hye-jeong"], "runtime_mins": 120, "imdb_rating": 8.3, "imdb_votes": "630,000+", "rotten_tomatoes_pct": 82, "metacritic_score": 77, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 15.4, "streaming_services": ["Apple TV", "Prime Video"], "plot": "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days."},
    {"title": "Inglourious Basterds", "year": 2009, "director": "Quentin Tarantino", "genres": ["Adventure", "Drama", "War"], "cast": ["Brad Pitt", "Diane Kruger", "Christoph Waltz"], "runtime_mins": 153, "imdb_rating": 8.4, "imdb_votes": "1,600,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 69, "letterboxd_rating": 4.3, "oscar_wins": 1, "box_office_million": 321.5, "streaming_services": ["Netflix", "Paramount+"], "plot": "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans."},
    {"title": "Good Will Hunting", "year": 1997, "director": "Gus Van Sant", "genres": ["Drama", "Romance"], "cast": ["Robin Williams", "Matt Damon", "Ben Affleck"], "runtime_mins": 126, "imdb_rating": 8.3, "imdb_votes": "1,080,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 70, "letterboxd_rating": 4.3, "oscar_wins": 2, "box_office_million": 225.9, "streaming_services": ["HBO Max", "Paramount+"], "plot": "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life."},

    # 61 - 70
    {"title": "Princess Mononoke", "year": 1997, "director": "Hayao Miyazaki", "genres": ["Animation", "Action", "Adventure", "Fantasy"], "cast": ["Yôji Matsuda", "Yuriko Ishida", "Yûko Tanaka"], "runtime_mins": 134, "imdb_rating": 8.3, "imdb_votes": "440,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 76, "letterboxd_rating": 4.4, "oscar_wins": 0, "box_office_million": 170.0, "streaming_services": ["HBO Max", "Netflix"], "plot": "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony."},
    {"title": "Once Upon a Time in the West", "year": 1968, "director": "Sergio Leone", "genres": ["Western"], "cast": ["Henry Fonda", "Charles Bronson", "Claudia Cardinale"], "runtime_mins": 165, "imdb_rating": 8.5, "imdb_votes": "350,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 82, "letterboxd_rating": 4.4, "oscar_wins": 0, "box_office_million": 5.4, "streaming_services": ["Paramount+", "Apple TV"], "plot": "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin."},
    {"title": "Requiem for a Dream", "year": 2000, "director": "Darren Aronofsky", "genres": ["Drama"], "cast": ["Ellen Burstyn", "Jared Leto", "Jennifer Connelly"], "runtime_mins": 102, "imdb_rating": 8.3, "imdb_votes": "910,000+", "rotten_tomatoes_pct": 79, "metacritic_score": 68, "letterboxd_rating": 4.1, "oscar_wins": 0, "box_office_million": 7.4, "streaming_services": ["Prime Video", "Apple TV"], "plot": "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep."},
    {"title": "American Beauty", "year": 1999, "director": "Sam Mendes", "genres": ["Drama"], "cast": ["Kevin Spacey", "Annette Bening", "Thora Birch"], "runtime_mins": 122, "imdb_rating": 8.3, "imdb_votes": "1,200,000+", "rotten_tomatoes_pct": 87, "metacritic_score": 84, "letterboxd_rating": 3.9, "oscar_wins": 5, "box_office_million": 356.3, "streaming_services": ["Paramount+", "Prime Video"], "plot": "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend."},
    {"title": "Citizen Kane", "year": 1941, "director": "Orson Welles", "genres": ["Drama", "Mystery"], "cast": ["Orson Welles", "Joseph Cotten", "Dorothy Comingore"], "runtime_mins": 119, "imdb_rating": 8.3, "imdb_votes": "460,000+", "rotten_tomatoes_pct": 99, "metacritic_score": 100, "letterboxd_rating": 4.3, "oscar_wins": 1, "box_office_million": 1.6, "streaming_services": ["HBO Max", "Criterion Channel"], "plot": "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance; 'Rosebud'."},
    {"title": "Vertigo", "year": 1958, "director": "Alfred Hitchcock", "genres": ["Mystery", "Romance", "Thriller"], "cast": ["James Stewart", "Kim Novak", "Barbara Bel Geddes"], "runtime_mins": 128, "imdb_rating": 8.3, "imdb_votes": "430,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 100, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 7.8, "streaming_services": ["Apple TV", "Prime Video"], "plot": "A former San Francisco police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail."},
    {"title": "North by Northwest", "year": 1959, "director": "Alfred Hitchcock", "genres": ["Action", "Adventure", "Mystery", "Thriller"], "cast": ["Cary Grant", "Eva Marie Saint", "James Mason"], "runtime_mins": 136, "imdb_rating": 8.3, "imdb_votes": "350,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 98, "letterboxd_rating": 4.2, "oscar_wins": 0, "box_office_million": 9.8, "streaming_services": ["HBO Max", "Apple TV"], "plot": "A New York City advertising executive goes on the run after being mistaken for a government agent by an aggressive gang of spies."},
    {"title": "A Clockwork Orange", "year": 1971, "director": "Stanley Kubrick", "genres": ["Crime", "Sci-Fi"], "cast": ["Malcolm McDowell", "Patrick Magee", "Michael Bates"], "runtime_mins": 136, "imdb_rating": 8.3, "imdb_votes": "870,000+", "rotten_tomatoes_pct": 88, "metacritic_score": 77, "letterboxd_rating": 4.1, "oscar_wins": 0, "box_office_million": 26.6, "streaming_services": ["HBO Max", "Apple TV"], "plot": "In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn't go as planned."},
    {"title": "Scarface", "year": 1983, "director": "Brian De Palma", "genres": ["Crime", "Drama"], "cast": ["Al Pacino", "Michelle Pfeiffer", "Steven Bauer"], "runtime_mins": 170, "imdb_rating": 8.3, "imdb_votes": "910,000+", "rotten_tomatoes_pct": 79, "metacritic_score": 65, "letterboxd_rating": 4.1, "oscar_wins": 0, "box_office_million": 66.0, "streaming_services": ["Netflix", "Prime Video"], "plot": "In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed."},
    {"title": "Full Metal Jacket", "year": 1987, "director": "Stanley Kubrick", "genres": ["Drama", "War"], "cast": ["Matthew Modine", "R. Lee Ermey", "Vincent D'Onofrio"], "runtime_mins": 116, "imdb_rating": 8.3, "imdb_votes": "780,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 76, "letterboxd_rating": 4.2, "oscar_wins": 0, "box_office_million": 46.4, "streaming_services": ["HBO Max", "Prime Video"], "plot": "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue."},

    # 71 - 80
    {"title": "Amadeus", "year": 1984, "director": "Milos Forman", "genres": ["Biography", "Drama", "Music"], "cast": ["F. Murray Abraham", "Tom Hulce", "Elizabeth Berridge"], "runtime_mins": 160, "imdb_rating": 8.4, "imdb_votes": "430,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 88, "letterboxd_rating": 4.4, "oscar_wins": 8, "box_office_million": 52.0, "streaming_services": ["HBO Max", "Apple TV"], "plot": "The life, success and troubles of Wolfgang Amadeus Mozart, as told by Antonio Salieri, the contemporaneous composer who was deeply jealous of Mozart's talent."},
    {"title": "Modern Times", "year": 1936, "director": "Charles Chaplin", "genres": ["Comedy", "Drama", "Romance"], "cast": ["Charles Chaplin", "Paulette Goddard", "Henry Bergman"], "runtime_mins": 87, "imdb_rating": 8.5, "imdb_votes": "260,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 96, "letterboxd_rating": 4.4, "oscar_wins": 0, "box_office_million": 1.5, "streaming_services": ["HBO Max", "Criterion Channel"], "plot": "The Tramp struggles to live in modern industrial society with the help of a young homeless woman."},
    {"title": "City Lights", "year": 1931, "director": "Charles Chaplin", "genres": ["Comedy", "Drama", "Romance"], "cast": ["Charles Chaplin", "Virginia Cherrill", "Florence Lee"], "runtime_mins": 87, "imdb_rating": 8.5, "imdb_votes": "190,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 99, "letterboxd_rating": 4.4, "oscar_wins": 0, "box_office_million": 5.0, "streaming_services": ["HBO Max", "Criterion Channel"], "plot": "With the help of an erratic rich man, a tramp falls in love with an impoverished blind flower girl."},
    {"title": "Heat", "year": 1995, "director": "Michael Mann", "genres": ["Action", "Crime", "Drama"], "cast": ["Al Pacino", "Robert De Niro", "Val Kilmer"], "runtime_mins": 170, "imdb_rating": 8.3, "imdb_votes": "730,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 76, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 187.4, "streaming_services": ["Netflix", "HBO Max"], "plot": "A group of high-end professional thieves start to feel the police pressure when they unwittingly leave a clue at their latest heist."},
    {"title": "L.A. Confidential", "year": 1997, "director": "Curtis Hanson", "genres": ["Crime", "Drama", "Mystery"], "cast": ["Kevin Spacey", "Russell Crowe", "Guy Pearce"], "runtime_mins": 138, "imdb_rating": 8.2, "imdb_votes": "610,000+", "rotten_tomatoes_pct": 99, "metacritic_score": 90, "letterboxd_rating": 4.2, "oscar_wins": 2, "box_office_million": 126.2, "streaming_services": ["Netflix", "Apple TV"], "plot": "As corruption grows in 1950s Los Angeles, three policemen - one straight-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice."},
    {"title": "Ran", "year": 1985, "director": "Akira Kurosawa", "genres": ["Action", "Drama", "War"], "cast": ["Tatsuya Nakadai", "Akira Terao", "Jinpachi Nezu"], "runtime_mins": 162, "imdb_rating": 8.2, "imdb_votes": "140,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 96, "letterboxd_rating": 4.5, "oscar_wins": 1, "box_office_million": 19.0, "streaming_services": ["Criterion Channel", "Apple TV"], "plot": "In Medieval Japan, an elderly warlord retires, handing over power to his three sons, which turns out to be disastrous."},
    {"title": "The Hunt (Jagten)", "year": 2012, "director": "Thomas Vinterberg", "genres": ["Drama"], "cast": ["Mads Mikkelsen", "Thomas Bo Larsen", "Annika Wedderkopp"], "runtime_mins": 115, "imdb_rating": 8.3, "imdb_votes": "360,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 77, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 18.3, "streaming_services": ["Prime Video", "Apple TV"], "plot": "A teacher lives a lonely life, all the while struggling over his son's custody. His life slowly gets better as he finds love, but his new luck is about to be brutally shattered by an innocent little lie."},
    {"title": "Bicycle Thieves", "year": 1948, "director": "Vittorio De Sica", "genres": ["Drama"], "cast": ["Lamberto Maggiorani", "Enzo Staiola", "Lianella Carell"], "runtime_mins": 89, "imdb_rating": 8.3, "imdb_votes": "175,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 90, "letterboxd_rating": 4.3, "oscar_wins": 1, "box_office_million": 0.4, "streaming_services": ["HBO Max", "Criterion Channel"], "plot": "In post-war Italy, a working-class man's bicycle is stolen. He and his son set out to find it, or else he will lose his job."},
    {"title": "Downfall", "year": 2004, "director": "Oliver Hirschbiegel", "genres": ["Biography", "Drama", "History", "War"], "cast": ["Bruno Ganz", "Alexandra Maria Lara", "Ulrich Matthes"], "runtime_mins": 156, "imdb_rating": 8.2, "imdb_votes": "385,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 82, "letterboxd_rating": 4.1, "oscar_wins": 0, "box_office_million": 92.2, "streaming_services": ["Prime Video", "Apple TV"], "plot": "Traudl Junge, the final secretary for Adolf Hitler, tells of the Nazi dictator's final days in his Berlin bunker at the end of WWII."},
    {"title": "Snatch", "year": 2000, "director": "Guy Ritchie", "genres": ["Comedy", "Crime"], "cast": ["Jason Statham", "Brad Pitt", "Benicio Del Toro"], "runtime_mins": 102, "imdb_rating": 8.2, "imdb_votes": "910,000+", "rotten_tomatoes_pct": 74, "metacritic_score": 55, "letterboxd_rating": 4.0, "oscar_wins": 0, "box_office_million": 83.6, "streaming_services": ["Netflix", "Prime Video"], "plot": "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and Jewish jewelers fight to track down a priceless stolen diamond."},

    # 81 - 90
    {"title": "Reservoir Dogs", "year": 1992, "director": "Quentin Tarantino", "genres": ["Crime", "Thriller"], "cast": ["Harvey Keitel", "Tim Roth", "Michael Madsen"], "runtime_mins": 99, "imdb_rating": 8.3, "imdb_votes": "1,070,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 81, "letterboxd_rating": 4.2, "oscar_wins": 0, "box_office_million": 2.8, "streaming_services": ["HBO Max", "Paramount+"], "plot": "When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant."},
    {"title": "The Great Dictator", "year": 1940, "director": "Charles Chaplin", "genres": ["Comedy", "Drama", "War"], "cast": ["Charles Chaplin", "Paulette Goddard", "Jack Oakie"], "runtime_mins": 125, "imdb_rating": 8.4, "imdb_votes": "245,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 90, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 5.0, "streaming_services": ["HBO Max", "Criterion Channel"], "plot": "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime."},
    {"title": "Lawrence of Arabia", "year": 1962, "director": "David Lean", "genres": ["Adventure", "Biography", "Drama"], "cast": ["Peter O'Toole", "Alec Guinness", "Anthony Quinn"], "runtime_mins": 218, "imdb_rating": 8.3, "imdb_votes": "315,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 100, "letterboxd_rating": 4.4, "oscar_wins": 7, "box_office_million": 70.0, "streaming_services": ["Criterion Channel", "Apple TV"], "plot": "The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I."},
    {"title": "Double Indemnity", "year": 1944, "director": "Billy Wilder", "genres": ["Crime", "Drama", "Film-Noir"], "cast": ["Fred MacMurray", "Barbara Stanwyck", "Edward G. Robinson"], "runtime_mins": 107, "imdb_rating": 8.3, "imdb_votes": "170,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 95, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 5.0, "streaming_services": ["Criterion Channel", "Apple TV"], "plot": "An insurance salesman is lured into a scheme involving fraud and murder by a captivating client."},
    {"title": "To Kill a Mockingbird", "year": 1962, "director": "Robert Mulligan", "genres": ["Crime", "Drama"], "cast": ["Gregory Peck", "John Megna", "Frank Overton"], "runtime_mins": 129, "imdb_rating": 8.3, "imdb_votes": "335,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 88, "letterboxd_rating": 4.2, "oscar_wins": 3, "box_office_million": 20.0, "streaming_services": ["Prime Video", "Apple TV"], "plot": "Atticus Finch, a widowed lawyer in Depression-era Alabama, defends a Black man against an undeserved rape charge."},
    {"title": "Eternal Sunshine of the Spotless Mind", "year": 2004, "director": "Michel Gondry", "genres": ["Drama", "Romance", "Sci-Fi"], "cast": ["Jim Carrey", "Kate Winslet", "Kirsten Dunst"], "runtime_mins": 108, "imdb_rating": 8.3, "imdb_votes": "1,080,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 89, "letterboxd_rating": 4.3, "oscar_wins": 1, "box_office_million": 74.0, "streaming_services": ["Netflix", "Apple TV"], "plot": "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories."},
    {"title": "Harakiri", "year": 1962, "director": "Masaki Kobayashi", "genres": ["Action", "Drama", "Mystery"], "cast": ["Tatsuya Nakadai", "Akira Ishihama", "Shima Iwashita"], "runtime_mins": 133, "imdb_rating": 8.6, "imdb_votes": "72,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 95, "letterboxd_rating": 4.7, "oscar_wins": 0, "box_office_million": 0.5, "streaming_services": ["Criterion Channel"], "plot": "When a ronin requesting seppuku at a feudal lord's palace is told of the brutal suicide of another ronin, he reveals a tragic connection."},
    {"title": "Das Boot", "year": 1981, "director": "Wolfgang Petersen", "genres": ["Drama", "War"], "cast": ["Jürgen Prochnow", "Herbert Grönemeyer", "Klaus Wennemann"], "runtime_mins": 149, "imdb_rating": 8.4, "imdb_votes": "270,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 86, "letterboxd_rating": 4.3, "oscar_wins": 0, "box_office_million": 84.9, "streaming_services": ["Prime Video", "Apple TV"], "plot": "A German submarine hunts allied shipping during the Battle of the Atlantic, dealing with claustrophobia and the immense pressure of underwater warfare."},
    {"title": "Come and See", "year": 1985, "director": "Elem Klimov", "genres": ["Drama", "War"], "cast": ["Aleksei Kravchenko", "Olga Mironova", "Liubomiras Laucevicius"], "runtime_mins": 142, "imdb_rating": 8.4, "imdb_votes": "115,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 90, "letterboxd_rating": 4.6, "oscar_wins": 0, "box_office_million": 0.8, "streaming_services": ["Criterion Channel", "YouTube"], "plot": "After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless Nazi forces in Byelorussia."},
    {"title": "Incendies", "year": 2010, "director": "Denis Villeneuve", "genres": ["Drama", "Mystery"], "cast": ["Lubna Azabal", "Mélissa Désormeaux-Poulin", "Maxim Gaudette"], "runtime_mins": 131, "imdb_rating": 8.3, "imdb_votes": "205,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 80, "letterboxd_rating": 4.4, "oscar_wins": 0, "box_office_million": 16.0, "streaming_services": ["Apple TV", "Prime Video"], "plot": "Twins travel to the Middle East to discover their family history and fulfill their mother's last wishes."},

    # 91 - 100
    {"title": "Blade Runner 2049", "year": 2017, "director": "Denis Villeneuve", "genres": ["Action", "Drama", "Mystery", "Sci-Fi"], "cast": ["Ryan Gosling", "Harrison Ford", "Ana de Armas"], "runtime_mins": 164, "imdb_rating": 8.0, "imdb_votes": "650,000+", "rotten_tomatoes_pct": 88, "metacritic_score": 81, "letterboxd_rating": 4.1, "oscar_wins": 2, "box_office_million": 267.7, "streaming_services": ["HBO Max", "Netflix"], "plot": "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years."},
    {"title": "Everything Everywhere All at Once", "year": 2022, "director": "Daniel Kwan, Daniel Scheinert", "genres": ["Action", "Adventure", "Comedy", "Sci-Fi"], "cast": ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"], "runtime_mins": 139, "imdb_rating": 7.8, "imdb_votes": "520,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 81, "letterboxd_rating": 4.2, "oscar_wins": 7, "box_office_million": 143.4, "streaming_services": ["Netflix", "Paramount+"], "plot": "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes."},
    {"title": "Top Gun: Maverick", "year": 2022, "director": "Joseph Kosinski", "genres": ["Action", "Drama"], "cast": ["Tom Cruise", "Miles Teller", "Jennifer Connelly"], "runtime_mins": 130, "imdb_rating": 8.2, "imdb_votes": "690,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 78, "letterboxd_rating": 4.1, "oscar_wins": 1, "box_office_million": 1495.7, "streaming_services": ["Paramount+", "Netflix"], "plot": "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past."},
    {"title": "The Batman", "year": 2022, "director": "Matt Reeves", "genres": ["Action", "Crime", "Drama"], "cast": ["Robert Pattinson", "Zoë Kravitz", "Jeffrey Wright"], "runtime_mins": 176, "imdb_rating": 7.8, "imdb_votes": "800,000+", "rotten_tomatoes_pct": 85, "metacritic_score": 72, "letterboxd_rating": 4.0, "oscar_wins": 0, "box_office_million": 772.2, "streaming_services": ["HBO Max", "Prime Video"], "plot": "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption."},
    {"title": "No Country for Old Men", "year": 2007, "director": "Ethan Coen, Joel Coen", "genres": ["Crime", "Drama", "Thriller"], "cast": ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin"], "runtime_mins": 122, "imdb_rating": 8.2, "imdb_votes": "1,060,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 92, "letterboxd_rating": 4.3, "oscar_wins": 4, "box_office_million": 171.6, "streaming_services": ["Paramount+", "Prime Video"], "plot": "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande."},
    {"title": "There Will Be Blood", "year": 2007, "director": "Paul Thomas Anderson", "genres": ["Drama"], "cast": ["Daniel Day-Lewis", "Paul Dano", "Ciarán Hinds"], "runtime_mins": 158, "imdb_rating": 8.2, "imdb_votes": "640,000+", "rotten_tomatoes_pct": 91, "metacritic_score": 93, "letterboxd_rating": 4.4, "oscar_wins": 2, "box_office_million": 76.2, "streaming_services": ["Paramount+", "Apple TV"], "plot": "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business."},
    {"title": "Fargo", "year": 1996, "director": "Joel Coen, Ethan Coen", "genres": ["Crime", "Drama", "Thriller"], "cast": ["William H. Macy", "Frances McDormand", "Steve Buscemi"], "runtime_mins": 98, "imdb_rating": 8.1, "imdb_votes": "730,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 85, "letterboxd_rating": 4.2, "oscar_wins": 2, "box_office_million": 60.6, "streaming_services": ["HBO Max", "Prime Video"], "plot": "Jerry Lundegaard's inept crime falls apart due to his and his henchmen's bungling and the persistent police work of the pregnant Marge Gunderson."},
    {"title": "The Grand Budapest Hotel", "year": 2014, "director": "Wes Anderson", "genres": ["Adventure", "Comedy", "Crime"], "cast": ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric"], "runtime_mins": 99, "imdb_rating": 8.1, "imdb_votes": "910,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 88, "letterboxd_rating": 4.2, "oscar_wins": 4, "box_office_million": 173.1, "streaming_services": ["Hulu", "Disney+"], "plot": "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge."},
    {"title": "Catch Me If You Can", "year": 2002, "director": "Steven Spielberg", "genres": ["Biography", "Crime", "Drama"], "cast": ["Leonardo DiCaprio", "Tom Hanks", "Christopher Walken"], "runtime_mins": 141, "imdb_rating": 8.1, "imdb_votes": "1,110,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 75, "letterboxd_rating": 4.0, "oscar_wins": 0, "box_office_million": 352.1, "streaming_services": ["Paramount+", "Netflix"], "plot": "Barely 21 yet, Frank Abagnale Jr. successfully performed cons worth millions of dollars by posing as a Pan Am pilot, a doctor, and a legal prosecutor."},
    {"title": "Spider-Man: Into the Spider-Verse", "year": 2018, "director": "Bob Persichetti, Peter Ramsey, Rodney Rothman", "genres": ["Animation", "Action", "Adventure"], "cast": ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"], "runtime_mins": 117, "imdb_rating": 8.4, "imdb_votes": "670,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 87, "letterboxd_rating": 4.4, "oscar_wins": 1, "box_office_million": 384.3, "streaming_services": ["Netflix", "Apple TV"], "plot": "Teen Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from alternate dimensions to stop a threat to all reality."}
]

# Generate Master DB with CineScore
MASTER_MOVIES_DB: List[Dict[str, Any]] = []
for idx, m in enumerate(RAW_TOP_100, 1):
    m_copy = dict(m)
    m_copy["id"] = f"tt_top100_{idx:03d}"
    m_copy["rank_top100"] = idx
    m_copy["cinescore"] = calculate_cinescore(m_copy["imdb_rating"], m_copy["rotten_tomatoes_pct"], m_copy["metacritic_score"], m_copy["letterboxd_rating"])
    MASTER_MOVIES_DB.append(m_copy)
