"""Top 100 TV Series and Legendary High-Rated Episodes Database.

Curated catalog of greatest television series and highest-rated episodes
of all time with ratings from IMDb, Rotten Tomatoes, and Metacritic.
"""

from typing import Dict, List, Any

def calculate_series_cinescore(imdb: float, rt: int, meta: int) -> float:
    """Calculates weighted CineScore (0-100) for TV series."""
    norm_imdb = (imdb / 10.0) * 100
    norm_rt = float(rt)
    norm_meta = float(meta)
    return round((norm_imdb * 0.45) + (norm_rt * 0.35) + (norm_meta * 0.20), 1)

RAW_TOP_100_SERIES: List[Dict[str, Any]] = [
    # 1 - 10
    {"title": "Breaking Bad", "start_year": 2008, "end_year": 2013, "creators": ["Vince Gilligan"], "genres": ["Crime", "Drama", "Thriller"], "seasons_count": 5, "episodes_count": 62, "imdb_rating": 9.5, "imdb_votes": "2,150,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 87, "streaming_services": ["Netflix", "AMC+"], "top_episode": "Ozymandias (S5E14 - 10.0)", "plot": "A chemistry teacher diagnosed with terminal lung cancer teams up with a former student to manufacture and sell methamphetamine."},
    {"title": "Planet Earth II", "start_year": 2016, "end_year": 2016, "creators": ["BBC Natural History"], "genres": ["Documentary"], "seasons_count": 1, "episodes_count": 6, "imdb_rating": 9.5, "imdb_votes": "160,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 96, "streaming_services": ["BBC iPlayer", "Max"], "top_episode": "Islands (S1E1 - 9.7)", "plot": "David Attenborough travels through the world's most breathtaking landscapes, showcasing animal survival."},
    {"title": "Planet Earth", "start_year": 2006, "end_year": 2006, "creators": ["Alastair Fothergill"], "genres": ["Documentary"], "seasons_count": 1, "episodes_count": 11, "imdb_rating": 9.4, "imdb_votes": "220,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 95, "streaming_services": ["Max"], "top_episode": "From Pole to Pole (S1E1 - 9.4)", "plot": "A groundbreaking journey across global wildernesses exploring species and ecosystems."},
    {"title": "Band of Brothers", "start_year": 2001, "end_year": 2001, "creators": ["Steven Spielberg", "Tom Hanks"], "genres": ["Drama", "History", "War"], "seasons_count": 1, "episodes_count": 10, "imdb_rating": 9.4, "imdb_votes": "520,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 87, "streaming_services": ["Max", "Netflix"], "top_episode": "Bastogne (S1E6 - 9.6)", "plot": "The story of Easy Company of the U.S. Army 101st Airborne Division and their mission in WWII Europe."},
    {"title": "Chernobyl", "start_year": 2019, "end_year": 2019, "creators": ["Craig Mazin"], "genres": ["Drama", "History", "Thriller"], "seasons_count": 1, "episodes_count": 5, "imdb_rating": 9.3, "imdb_votes": "870,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 82, "streaming_services": ["Max"], "top_episode": "Vichnaya Pamyat (S1E5 - 9.9)", "plot": "The harrowing true story of the 1986 nuclear disaster in Soviet Ukraine and the courageous sacrifices made to contain it."},
    {"title": "The Wire", "start_year": 2002, "end_year": 2008, "creators": ["David Simon"], "genres": ["Crime", "Drama", "Thriller"], "seasons_count": 5, "episodes_count": 60, "imdb_rating": 9.3, "imdb_votes": "380,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 91, "streaming_services": ["Max"], "top_episode": "Middle Ground (S3E11 - 9.7)", "plot": "The Baltimore drug trade explored from the perspectives of police officers, drug kingpins, schools, and journalists."},
    {"title": "The Sopranos", "start_year": 1999, "end_year": 2007, "creators": ["David Chase"], "genres": ["Crime", "Drama"], "seasons_count": 6, "episodes_count": 86, "imdb_rating": 9.2, "imdb_votes": "460,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 97, "streaming_services": ["Max"], "top_episode": "Pine Barrens (S3E11 - 9.7)", "plot": "New Jersey mob boss Tony Soprano balances personal family crises with running a violent criminal syndicate."},
    {"title": "Game of Thrones", "start_year": 2011, "end_year": 2019, "creators": ["David Benioff", "D.B. Weiss"], "genres": ["Action", "Adventure", "Drama", "Fantasy"], "seasons_count": 8, "episodes_count": 73, "imdb_rating": 9.2, "imdb_votes": "2,350,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 86, "streaming_services": ["Max"], "top_episode": "Battle of the Bastards (S6E9 - 9.9)", "plot": "Nine noble houses wage brutal warfare for the Iron Throne of Westeros while an ancient menace awakens in the far North."},
    {"title": "Better Call Saul", "start_year": 2015, "end_year": 2022, "creators": ["Vince Gilligan", "Peter Gould"], "genres": ["Crime", "Drama"], "seasons_count": 6, "episodes_count": 63, "imdb_rating": 9.0, "imdb_votes": "650,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 86, "streaming_services": ["Netflix"], "top_episode": "Plan and Execution (S6E7 - 9.9)", "plot": "The tragic transformation of earnest public defender Jimmy McGill into unscrupulous cartel fixer Saul Goodman."},
    {"title": "Sherlock", "start_year": 2010, "end_year": 2017, "creators": ["Mark Gatiss", "Steven Moffat"], "genres": ["Crime", "Drama", "Mystery"], "seasons_count": 4, "episodes_count": 13, "imdb_rating": 9.1, "imdb_votes": "990,000+", "rotten_tomatoes_pct": 78, "metacritic_score": 88, "streaming_services": ["BBC iPlayer", "Prime Video"], "top_episode": "The Reichenbach Fall (S2E3 - 9.7)", "plot": "A dazzling 21st-century reinterpretation of Sherlock Holmes and Dr. John Watson cracking bizarre cases in London."},

    # 11 - 20
    {"title": "The Twilight Zone", "start_year": 1959, "end_year": 1964, "creators": ["Rod Serling"], "genres": ["Drama", "Fantasy", "Horror", "Mystery"], "seasons_count": 5, "episodes_count": 156, "imdb_rating": 9.1, "imdb_votes": "95,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 93, "streaming_services": ["Paramount+"], "top_episode": "Time Enough at Last (S1E8 - 9.2)", "plot": "Ordinary men and women step beyond the veil of reality into paradoxical realms of the mind and morality."},
    {"title": "Succession", "start_year": 2018, "end_year": 2023, "creators": ["Jesse Armstrong"], "genres": ["Comedy", "Drama"], "seasons_count": 4, "episodes_count": 39, "imdb_rating": 8.9, "imdb_votes": "290,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 89, "streaming_services": ["Max"], "top_episode": "Connor's Wedding (S4E3 - 9.9)", "plot": "The toxic, power-hungry heirs of media mogul Logan Roy battle viciously for control of global empire Waystar RoyCo."},
    {"title": "True Detective", "start_year": 2014, "end_year": 2024, "creators": ["Nic Pizzolatto"], "genres": ["Crime", "Drama", "Mystery"], "seasons_count": 4, "episodes_count": 30, "imdb_rating": 8.9, "imdb_votes": "650,000+", "rotten_tomatoes_pct": 78, "metacritic_score": 75, "streaming_services": ["Max"], "top_episode": "Who Goes There (S1E4 - 9.7)", "plot": "Anthology investigating harrowing occult crimes across American history, beginning with Rust Cohle and Marty Hart."},
    {"title": "Fargo", "start_year": 2014, "end_year": 2024, "creators": ["Noah Hawley"], "genres": ["Crime", "Drama", "Thriller"], "seasons_count": 5, "episodes_count": 51, "imdb_rating": 8.9, "imdb_votes": "420,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 85, "streaming_services": ["Hulu"], "top_episode": "The Castle (S2E9 - 9.6)", "plot": "Anthology chronicles eccentric Midwestern crime cases, bumbling criminals, and steadfast small-town detectives."},
    {"title": "Firefly", "start_year": 2002, "end_year": 2003, "creators": ["Joss Whedon"], "genres": ["Adventure", "Drama", "Sci-Fi"], "seasons_count": 1, "episodes_count": 14, "imdb_rating": 8.9, "imdb_votes": "280,000+", "rotten_tomatoes_pct": 77, "metacritic_score": 77, "streaming_services": ["Hulu"], "top_episode": "Out of Gas (S1E8 - 9.3)", "plot": "Five hundred years in the future, the renegade crew of the transport ship Serenity tackles perilous frontier jobs."},
    {"title": "The Last of Us", "start_year": 2023, "end_year": 2025, "creators": ["Craig Mazin", "Neil Druckmann"], "genres": ["Action", "Adventure", "Drama", "Sci-Fi"], "seasons_count": 1, "episodes_count": 9, "imdb_rating": 8.8, "imdb_votes": "590,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 84, "streaming_services": ["Max"], "top_episode": "Long, Long Time (S1E3 - 9.2)", "plot": "Grizzled smuggler Joel escorts immune teenager Ellie across a post-apocalyptic America ravaged by fungal monsters."},
    {"title": "Dark", "start_year": 2017, "end_year": 2020, "creators": ["Baran bo Odar", "Jantje Friese"], "genres": ["Crime", "Drama", "Mystery", "Sci-Fi"], "seasons_count": 3, "episodes_count": 26, "imdb_rating": 8.7, "imdb_votes": "460,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 82, "streaming_services": ["Netflix"], "top_episode": "An End and a Beginning (S2E8 - 9.7)", "plot": "A missing child in a German town reveals a mind-bending time-travel conspiracy spanning four interconnected families."},
    {"title": "Black Mirror", "start_year": 2011, "end_year": 2025, "creators": ["Charlie Brooker"], "genres": ["Drama", "Mystery", "Sci-Fi", "Thriller"], "seasons_count": 6, "episodes_count": 27, "imdb_rating": 8.7, "imdb_votes": "640,000+", "rotten_tomatoes_pct": 83, "metacritic_score": 76, "streaming_services": ["Netflix"], "top_episode": "White Christmas (S2E4 - 9.1)", "plot": "Dystopian anthology exploring how emerging technological innovations warp human nature, society, and relationships."},
    {"title": "Severance", "start_year": 2022, "end_year": 2025, "creators": ["Dan Erickson"], "genres": ["Drama", "Mystery", "Sci-Fi", "Thriller"], "seasons_count": 2, "episodes_count": 19, "imdb_rating": 8.7, "imdb_votes": "230,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 83, "streaming_services": ["Apple TV+"], "top_episode": "The We We Are (S1E9 - 9.7)", "plot": "Lumon Industries employees undergo brain surgery to cleanly sever workplace memories from outside personal lives."},
    {"title": "Stranger Things", "start_year": 2016, "end_year": 2025, "creators": ["Matt Duffer", "Ross Duffer"], "genres": ["Drama", "Fantasy", "Horror", "Sci-Fi"], "seasons_count": 4, "episodes_count": 34, "imdb_rating": 8.7, "imdb_votes": "1,400,000+", "rotten_tomatoes_pct": 91, "metacritic_score": 74, "streaming_services": ["Netflix"], "top_episode": "Chapter Four: Dear Billy (S4E4 - 9.6)", "plot": "Kids in 1980s Indiana uncover clandestine government experiments, an alternate realm called the Upside Down, and Eleven."},

    # 21 - 30
    {"title": "Peaky Blinders", "start_year": 2013, "end_year": 2022, "creators": ["Steven Knight"], "genres": ["Crime", "Drama"], "seasons_count": 6, "episodes_count": 36, "imdb_rating": 8.8, "imdb_votes": "660,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 77, "streaming_services": ["Netflix", "BBC iPlayer"], "top_episode": "Lock and Key (S6E6 - 9.3)", "plot": "War veteran Thomas Shelby leads the razor-capped Peaky Blinders gang from Birmingham streets to the corridors of parliament."},
    {"title": "The Office (US)", "start_year": 2005, "end_year": 2013, "creators": ["Greg Daniels"], "genres": ["Comedy"], "seasons_count": 9, "episodes_count": 201, "imdb_rating": 9.0, "imdb_votes": "730,000+", "rotten_tomatoes_pct": 81, "metacritic_score": 66, "streaming_services": ["Peacock", "Netflix"], "top_episode": "Dinner Party (S4E9 - 9.5)", "plot": "The daily hilarity, romantic awkwardness, and workplace comedy at Dunder Mifflin paper company branch in Scranton."},
    {"title": "House of the Dragon", "start_year": 2022, "end_year": 2026, "creators": ["Ryan J. Condal", "George R.R. Martin"], "genres": ["Action", "Adventure", "Drama", "Fantasy"], "seasons_count": 2, "episodes_count": 18, "imdb_rating": 8.4, "imdb_votes": "430,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 73, "streaming_services": ["Max"], "top_episode": "The Lord of the Tides (S1E8 - 9.3)", "plot": "The devastating Dance of the Dragons civil war tears House Targaryen apart nearly two centuries before Game of Thrones."},
    {"title": "Fleabag", "start_year": 2016, "end_year": 2019, "creators": ["Phoebe Waller-Bridge"], "genres": ["Comedy", "Drama"], "seasons_count": 2, "episodes_count": 12, "imdb_rating": 8.7, "imdb_votes": "210,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 92, "streaming_services": ["Prime Video"], "top_episode": "Episode 2.1 (S2E1 - 9.3)", "plot": "A witty, unfiltered London woman navigates grief, family dysfunction, and an unexpected attraction to a charming priest."},
    {"title": "Mad Men", "start_year": 2007, "end_year": 2015, "creators": ["Matthew Weiner"], "genres": ["Drama"], "seasons_count": 7, "episodes_count": 92, "imdb_rating": 8.7, "imdb_votes": "280,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 86, "streaming_services": ["AMC+", "Prime Video"], "top_episode": "The Suitcase (S4E7 - 9.7)", "plot": "Enigmatic creative director Don Draper reigns over Madison Avenue advertising during the turbulent shifts of the 1960s."},
    {"title": "The Crown", "start_year": 2016, "end_year": 2023, "creators": ["Peter Morgan"], "genres": ["Biography", "Drama", "History"], "seasons_count": 6, "episodes_count": 60, "imdb_rating": 8.6, "imdb_votes": "250,000+", "rotten_tomatoes_pct": 86, "metacritic_score": 81, "streaming_services": ["Netflix"], "top_episode": "Aberfan (S3E3 - 9.0)", "plot": "The private lives, sovereign duties, and political challenges of Queen Elizabeth II from marriage to the 21st century."},
    {"title": "Mindhunter", "start_year": 2017, "end_year": 2019, "creators": ["Joe Penhall"], "genres": ["Crime", "Drama", "Mystery", "Thriller"], "seasons_count": 2, "episodes_count": 19, "imdb_rating": 8.6, "imdb_votes": "340,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 79, "streaming_services": ["Netflix"], "top_episode": "Episode 1.10 (S1E10 - 9.2)", "plot": "Pioneering FBI agents conduct in-depth interviews with imprisoned serial killers to formulate modern criminal profiling."},
    {"title": "Narcos", "start_year": 2015, "end_year": 2017, "creators": ["Carlo Bernard", "Chris Brancato"], "genres": ["Biography", "Crime", "Drama"], "seasons_count": 3, "episodes_count": 30, "imdb_rating": 8.8, "imdb_votes": "470,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 77, "streaming_services": ["Netflix"], "top_episode": "Al Fin Cayó! (S2E10 - 9.5)", "plot": "DEA agents track the violent rise and fall of Pablo Escobar and the Medellín cocaine cartel in Colombia."},
    {"title": "Mr. Robot", "start_year": 2015, "end_year": 2019, "creators": ["Sam Esmail"], "genres": ["Crime", "Drama", "Thriller"], "seasons_count": 4, "episodes_count": 45, "imdb_rating": 8.5, "imdb_votes": "410,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 80, "streaming_services": ["Prime Video"], "top_episode": "407 Proxy Authentication Required (S4E7 - 9.9)", "plot": "Morphine-addicted hacker Elliot Alderson is recruited by fsociety to topple corporate conglomerate E Corp."},
    {"title": "Twin Peaks", "start_year": 1990, "end_year": 1991, "creators": ["Mark Frost", "David Lynch"], "genres": ["Crime", "Drama", "Mystery"], "seasons_count": 2, "episodes_count": 30, "imdb_rating": 8.8, "imdb_votes": "220,000+", "rotten_tomatoes_pct": 82, "metacritic_score": 85, "streaming_services": ["Paramount+"], "top_episode": "Lonely Souls (S2E7 - 9.5)", "plot": "Eccentric FBI Special Agent Dale Cooper investigates the surreal murder of homecoming queen Laura Palmer in a quirky town."},

    # 31 - 40
    {"title": "Lost", "start_year": 2004, "end_year": 2010, "creators": ["J.J. Abrams", "Damon Lindelof"], "genres": ["Adventure", "Drama", "Fantasy", "Mystery"], "seasons_count": 6, "episodes_count": 121, "imdb_rating": 8.3, "imdb_votes": "610,000+", "rotten_tomatoes_pct": 85, "metacritic_score": 84, "streaming_services": ["Hulu", "Disney+"], "top_episode": "The Constant (S4E5 - 9.7)", "plot": "Oceanic Flight 815 plane crash survivors struggle to stay alive on an island filled with polar bears, smoke monsters, and bunkers."},
    {"title": "Dexter", "start_year": 2006, "end_year": 2013, "creators": ["James Manos Jr."], "genres": ["Crime", "Drama", "Mystery"], "seasons_count": 8, "episodes_count": 96, "imdb_rating": 8.6, "imdb_votes": "780,000+", "rotten_tomatoes_pct": 71, "metacritic_score": 75, "streaming_services": ["Paramount+", "Showtime"], "top_episode": "The Getaway (S4E12 - 9.8)", "plot": "Miami Metro blood spatter analyst Dexter Morgan leads a secret vigilante double-life hunting criminals who escaped justice."},
    {"title": "Friends", "start_year": 1994, "end_year": 2004, "creators": ["David Crane", "Marta Kauffman"], "genres": ["Comedy", "Romance"], "seasons_count": 10, "episodes_count": 236, "imdb_rating": 8.9, "imdb_votes": "1,080,000+", "rotten_tomatoes_pct": 78, "metacritic_score": 65, "streaming_services": ["Max"], "top_episode": "The One with the Embryos (S4E12 - 9.4)", "plot": "Six tight-knit young adults live, love, and experience unforgettable laughs in New York City across a decade."},
    {"title": "BoJack Horseman", "start_year": 2014, "end_year": 2020, "creators": ["Raphael Bob-Waksberg"], "genres": ["Animation", "Comedy", "Drama"], "seasons_count": 6, "episodes_count": 77, "imdb_rating": 8.8, "imdb_votes": "190,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 82, "streaming_services": ["Netflix"], "top_episode": "The View from Halfway Down (S6E15 - 9.9)", "plot": "A humanoid horse and washed-up 90s sitcom star grapples with existential depression, addiction, and redemption in Hollywoo."},
    {"title": "Rome", "start_year": 2005, "end_year": 2007, "creators": ["Bruno Heller"], "genres": ["Action", "Drama", "History"], "seasons_count": 2, "episodes_count": 22, "imdb_rating": 8.7, "imdb_votes": "180,000+", "rotten_tomatoes_pct": 86, "metacritic_score": 76, "streaming_services": ["Max"], "top_episode": "De Patre Vostro (S2E10 - 9.3)", "plot": "Centurion Lucius Vorenus and Legionary Titus Pullo witness the epic collapse of the Roman Republic and Julius Caesar's ascendance."},
    {"title": "Six Feet Under", "start_year": 2001, "end_year": 2005, "creators": ["Alan Ball"], "genres": ["Comedy", "Drama"], "seasons_count": 5, "episodes_count": 63, "imdb_rating": 8.7, "imdb_votes": "150,000+", "rotten_tomatoes_pct": 81, "metacritic_score": 74, "streaming_services": ["Max", "Netflix"], "top_episode": "Everyone's Waiting (S5E12 - 9.9)", "plot": "The Fisher family runs a mortuary business in Los Angeles, exploring profound truths about mortality, love, and grief."},
    {"title": "When They See Us", "start_year": 2019, "end_year": 2019, "creators": ["Ava DuVernay"], "genres": ["Biography", "Crime", "Drama", "History"], "seasons_count": 1, "episodes_count": 4, "imdb_rating": 8.9, "imdb_votes": "140,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 86, "streaming_services": ["Netflix"], "top_episode": "Part Four (S1E4 - 9.4)", "plot": "The true account of five Harlem teenagers wrongfully convicted of the 1989 Central Park jogger attack and their fight for justice."},
    {"title": "Deadwood", "start_year": 2004, "end_year": 2006, "creators": ["David Milch"], "genres": ["Crime", "Drama", "Western"], "seasons_count": 3, "episodes_count": 36, "imdb_rating": 8.6, "imdb_votes": "120,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 85, "streaming_services": ["Max"], "top_episode": "Tell Him Something Pretty (S3E12 - 9.0)", "plot": "Al Swearengen and Seth Bullock navigate gold rush lawlessness and lethal greed in the frontier town of Deadwood, South Dakota."},
    {"title": "Boardwalk Empire", "start_year": 2010, "end_year": 2014, "creators": ["Terence Winter"], "genres": ["Crime", "Drama"], "seasons_count": 5, "episodes_count": 56, "imdb_rating": 8.6, "imdb_votes": "205,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 83, "streaming_services": ["Max"], "top_episode": "To the Lost (S2E12 - 9.4)", "plot": "Treasurer Enoch 'Nucky' Thompson controls Atlantic City with backroom politics and bootlegging profits during Prohibition."},
    {"title": "Justified", "start_year": 2010, "end_year": 2015, "creators": ["Graham Yost"], "genres": ["Action", "Crime", "Drama"], "seasons_count": 6, "episodes_count": 78, "imdb_rating": 8.6, "imdb_votes": "115,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 86, "streaming_services": ["Hulu"], "top_episode": "Bloody Harlan (S2E13 - 9.3)", "plot": "U.S. Marshal Raylan Givens dispenses 19th-century frontier justice to Harlan County outlaws, including Boyd Crowder."},

    # 41 - 50
    {"title": "Downton Abbey", "start_year": 2010, "end_year": 2015, "creators": ["Julian Fellowes"], "genres": ["Drama", "Romance"], "seasons_count": 6, "episodes_count": 52, "imdb_rating": 8.7, "imdb_votes": "220,000+", "rotten_tomatoes_pct": 86, "metacritic_score": 84, "streaming_services": ["Peacock", "Prime Video"], "top_episode": "Episode 3.4 (S3E4 - 9.2)", "plot": "The aristocratic Crawley family and their devoted servants experience historical milestones from the Titanic sinking to WWI."},
    {"title": "It's Always Sunny in Philadelphia", "start_year": 2005, "end_year": 2025, "creators": ["Rob McElhenney"], "genres": ["Comedy"], "seasons_count": 16, "episodes_count": 170, "imdb_rating": 8.8, "imdb_votes": "250,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 75, "streaming_services": ["Hulu"], "top_episode": "The Nightman Cometh (S4E13 - 9.7)", "plot": "Five depraved friends operate Paddy's Pub in South Philly, hatching absurd schemes with zero morals or self-awareness."},
    {"title": "Parks and Recreation", "start_year": 2009, "end_year": 2015, "creators": ["Greg Daniels", "Michael Schur"], "genres": ["Comedy"], "seasons_count": 7, "episodes_count": 125, "imdb_rating": 8.6, "imdb_votes": "285,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 78, "streaming_services": ["Peacock"], "top_episode": "One Last Ride (S7E12 - 9.4)", "plot": "Indomitable bureaucrat Leslie Knope and her oddball colleagues work to beautify Pawnee, Indiana."},
    {"title": "Arcane", "start_year": 2021, "end_year": 2024, "creators": ["Christian Linke", "Alex Yee"], "genres": ["Animation", "Action", "Adventure", "Sci-Fi"], "seasons_count": 2, "episodes_count": 18, "imdb_rating": 9.0, "imdb_votes": "300,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 90, "streaming_services": ["Netflix"], "top_episode": "The Monster You Created (S1E9 - 9.6)", "plot": "Sisters Vi and Jinx find themselves on opposing sides of a devastating tech war between glittering Piltover and gritty Zaun."},
    {"title": "Shōgun", "start_year": 2024, "end_year": 2026, "creators": ["Rachel Kondo", "Justin Marks"], "genres": ["Adventure", "Drama", "History", "War"], "seasons_count": 1, "episodes_count": 10, "imdb_rating": 8.7, "imdb_votes": "185,000+", "rotten_tomatoes_pct": 99, "metacritic_score": 85, "streaming_services": ["Hulu", "Disney+"], "top_episode": "Crimson Sky (S1E9 - 9.5)", "plot": "English navigator John Blackthorne is shipwrecked in 1600 feudal Japan, becoming a vital pawn for warlord Lord Toranaga."},
    {"title": "The Bear", "start_year": 2022, "end_year": 2025, "creators": ["Christopher Storer"], "genres": ["Comedy", "Drama"], "seasons_count": 3, "episodes_count": 28, "imdb_rating": 8.6, "imdb_votes": "260,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 88, "streaming_services": ["Hulu", "Disney+"], "top_episode": "Forks (S2E7 - 9.7)", "plot": "Michelin-starred young chef Carmy Berzatto returns home to rescue his deceased brother's chaotic Chicago beef sandwich shop."},
    {"title": "Ted Lasso", "start_year": 2020, "end_year": 2023, "creators": ["Bill Lawrence", "Jason Sudeikis"], "genres": ["Comedy", "Drama", "Sport"], "seasons_count": 3, "episodes_count": 34, "imdb_rating": 8.8, "imdb_votes": "340,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 79, "streaming_services": ["Apple TV+"], "top_episode": "Rainbow (S2E5 - 9.3)", "plot": "An incessantly folksy American college football coach takes the helm of struggling English soccer club AFC Richmond."},
    {"title": "Hannibal", "start_year": 2013, "end_year": 2015, "creators": ["Bryan Fuller"], "genres": ["Crime", "Drama", "Horror", "Mystery"], "seasons_count": 3, "episodes_count": 39, "imdb_rating": 8.5, "imdb_votes": "285,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 77, "streaming_services": ["Hulu", "AMC+"], "top_episode": "Mizumono (S2E13 - 9.8)", "plot": "Unstable FBI profiler Will Graham matches wits with refined cannibalistic psychiatrist Dr. Hannibal Lecter in a lethal dance."},
    {"title": "Community", "start_year": 2009, "end_year": 2015, "creators": ["Dan Harmon"], "genres": ["Comedy"], "seasons_count": 6, "episodes_count": 110, "imdb_rating": 8.5, "imdb_votes": "290,000+", "rotten_tomatoes_pct": 88, "metacritic_score": 69, "streaming_services": ["Netflix", "Hulu"], "top_episode": "Remedial Chaos Theory (S3E4 - 9.8)", "plot": "Disbarred lawyer Jeff Winger forms a study group at Greendale Community College that descends into high-concept pop meta humor."},
    {"title": "Yellowstone", "start_year": 2018, "end_year": 2024, "creators": ["Taylor Sheridan"], "genres": ["Drama", "Western"], "seasons_count": 5, "episodes_count": 53, "imdb_rating": 8.7, "imdb_votes": "240,000+", "rotten_tomatoes_pct": 84, "metacritic_score": 60, "streaming_services": ["Peacock", "Paramount+"], "top_episode": "Resurrection Day (S2E7 - 9.4)", "plot": "Patriarch John Dutton defends the largest contiguous cattle ranch in the United States from developers and reservations."},

    # 51 - 60
    {"title": "Seinfeld", "start_year": 1989, "end_year": 1998, "creators": ["Larry David", "Jerry Seinfeld"], "genres": ["Comedy"], "seasons_count": 9, "episodes_count": 180, "imdb_rating": 8.9, "imdb_votes": "360,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 84, "streaming_services": ["Netflix"], "top_episode": "The Contest (S4E11 - 9.6)", "plot": "Stand-up comedian Jerry Seinfeld and his eccentric New York friends navigate everyday trivialities with zero sentimentality."},
    {"title": "Curb Your Enthusiasm", "start_year": 2000, "end_year": 2024, "creators": ["Larry David"], "genres": ["Comedy"], "seasons_count": 12, "episodes_count": 120, "imdb_rating": 8.8, "imdb_votes": "150,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 84, "streaming_services": ["Max"], "top_episode": "Palestinian Chicken (S8E3 - 9.4)", "plot": "Seinfeld co-creator Larry David gets entangled in endless socially awkward misunderstandings in wealthy Los Angeles."},
    {"title": "Barry", "start_year": 2018, "end_year": 2023, "creators": ["Alec Berg", "Bill Hader"], "genres": ["Comedy", "Crime", "Drama"], "seasons_count": 4, "episodes_count": 32, "imdb_rating": 8.4, "imdb_votes": "120,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 88, "streaming_services": ["Max"], "top_episode": "ronny/lily (S2E5 - 9.8)", "plot": "A depressed Midwest hitman travels to Los Angeles for a contract kill and discovers an unexpected passion for theatrical acting."},
    {"title": "The Boys", "start_year": 2019, "end_year": 2026, "creators": ["Eric Kripke"], "genres": ["Action", "Comedy", "Drama", "Sci-Fi"], "seasons_count": 4, "episodes_count": 32, "imdb_rating": 8.7, "imdb_votes": "690,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 77, "streaming_services": ["Prime Video"], "top_episode": "Herogasm (S3E6 - 9.6)", "plot": "A gritty team of vigilantes sets out to expose the grotesque corruption and corporate atrocities of corrupt superheroes led by Homelander."},
    {"title": "Sherlock Holmes (1984)", "start_year": 1984, "end_year": 1994, "creators": ["John Hawkesworth"], "genres": ["Crime", "Drama", "Mystery"], "seasons_count": 7, "episodes_count": 41, "imdb_rating": 8.7, "imdb_votes": "28,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 85, "streaming_services": ["BritBox"], "top_episode": "The Sign of Four (S2E1 - 8.8)", "plot": "Jeremy Brett gives the definitive, atmospheric portrayal of Sir Arthur Conan Doyle's Victorian consulting detective."},
    {"title": "The Shield", "start_year": 2002, "end_year": 2008, "creators": ["Shawn Ryan"], "genres": ["Crime", "Drama", "Thriller"], "seasons_count": 7, "episodes_count": 88, "imdb_rating": 8.7, "imdb_votes": "90,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 83, "streaming_services": ["Hulu"], "top_episode": "Family Meeting (S7E13 - 9.8)", "plot": "Detective Vic Mackey commands an elite, violently corrupt Strike Team operating on the fringes of the law in Los Angeles."},
    {"title": "Oz", "start_year": 1997, "end_year": 2003, "creators": ["Tom Fontana"], "genres": ["Crime", "Drama", "Thriller"], "seasons_count": 6, "episodes_count": 56, "imdb_rating": 8.7, "imdb_votes": "105,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 75, "streaming_services": ["Max"], "top_episode": "Straight Life (S1E5 - 8.8)", "plot": "The daily brutality and factional warfare within the experimental Emerald City wing of Oswald Maximum Security Penitentiary."},
    {"title": "Battlestar Galactica", "start_year": 2004, "end_year": 2009, "creators": ["Glen A. Larson", "Ronald D. Moore"], "genres": ["Action", "Adventure", "Drama", "Sci-Fi"], "seasons_count": 4, "episodes_count": 76, "imdb_rating": 8.7, "imdb_votes": "175,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 89, "streaming_services": ["Peacock", "Prime Video"], "top_episode": "Exodus: Part 2 (S3E4 - 9.5)", "plot": "When Cylon androids annihilate the Twelve Colonies, Commander Adama leads the ragtag fleet of survivors seeking Earth."},
    {"title": "Line of Duty", "start_year": 2012, "end_year": 2021, "creators": ["Jed Mercurio"], "genres": ["Crime", "Drama", "Mystery", "Thriller"], "seasons_count": 6, "episodes_count": 36, "imdb_rating": 8.7, "imdb_votes": "70,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 87, "streaming_services": ["BritBox", "BBC iPlayer"], "top_episode": "Episode 3.6 (S3E6 - 9.6)", "plot": "Police anti-corruption unit AC-12 investigates crooked senior officers intertwined with organized crime networks."},
    {"title": "Narcos: Mexico", "start_year": 2018, "end_year": 2021, "creators": ["Carlo Bernard", "Chris Brancato"], "genres": ["Crime", "Drama"], "seasons_count": 3, "episodes_count": 30, "imdb_rating": 8.4, "imdb_votes": "115,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 80, "streaming_services": ["Netflix"], "top_episode": "881 Lope de Vega (S1E9 - 9.3)", "plot": "Witness the rise of the Guadalajara Cartel in the 1980s as Félix Gallardo unites traffickers and DEA agent Kiki Camarena fights back."},

    # 61 - 70
    {"title": "House M.D.", "start_year": 2004, "end_year": 2012, "creators": ["David Shore"], "genres": ["Drama", "Mystery"], "seasons_count": 8, "episodes_count": 177, "imdb_rating": 8.7, "imdb_votes": "510,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 75, "streaming_services": ["Hulu", "Prime Video"], "top_episode": "House's Head (S4E15 - 9.8)", "plot": "Misanthropic, Vicodin-reliant medical genius Dr. Gregory House and his team diagnose perplexing medical mysteries."},
    {"title": "The Mandalorian", "start_year": 2019, "end_year": 2025, "creators": ["Jon Favreau"], "genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"], "seasons_count": 3, "episodes_count": 24, "imdb_rating": 8.6, "imdb_votes": "590,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 71, "streaming_services": ["Disney+"], "top_episode": "Chapter 16: The Rescue (S2E8 - 9.8)", "plot": "A lone bounty hunter navigates the lawless outer reaches of the galaxy protecting a mysterious Force-sensitive child named Grogu."},
    {"title": "Andor", "start_year": 2022, "end_year": 2025, "creators": ["Tony Gilroy"], "genres": ["Action", "Adventure", "Drama", "Sci-Fi"], "seasons_count": 1, "episodes_count": 12, "imdb_rating": 8.4, "imdb_votes": "180,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 74, "streaming_services": ["Disney+"], "top_episode": "One Way Out (S1E10 - 9.6)", "plot": "Cassian Andor discovers the difference he can make in the nascent rebellion against the crushing fascism of the Galactic Empire."},
    {"title": "Atlanta", "start_year": 2016, "end_year": 2022, "creators": ["Donald Glover"], "genres": ["Comedy", "Drama", "Music"], "seasons_count": 4, "episodes_count": 41, "imdb_rating": 8.6, "imdb_votes": "95,000+", "rotten_tomatoes_pct": 98, "metacritic_score": 90, "streaming_services": ["Hulu"], "top_episode": "Teddy Perkins (S2E6 - 9.7)", "plot": "Two cousins navigate the Atlanta rap scene while confronting surreal social and economic issues."},
    {"title": "Primal", "start_year": 2019, "end_year": 2024, "creators": ["Genndy Tartakovsky"], "genres": ["Animation", "Action", "Adventure", "Fantasy"], "seasons_count": 2, "episodes_count": 20, "imdb_rating": 8.7, "imdb_votes": "55,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 87, "streaming_services": ["Max"], "top_episode": "Plague of Madness (S1E7 - 9.5)", "plot": "A caveman at the dawn of evolution and a female tyrannosaurus bond over shared tragedy to survive a brutal prehistoric world."},
    {"title": "Broadchurch", "start_year": 2013, "end_year": 2017, "creators": ["Chris Chibnall"], "genres": ["Crime", "Drama", "Mystery"], "seasons_count": 3, "episodes_count": 24, "imdb_rating": 8.4, "imdb_votes": "135,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 85, "streaming_services": ["Prime Video"], "top_episode": "Episode 1.8 (S1E8 - 9.3)", "plot": "The murder of a young boy in a small Dorset coastal town draws detectives Alec Hardy and Ellie Miller into a grief-stricken mystery."},
    {"title": "The Americans", "start_year": 2013, "end_year": 2018, "creators": ["Joseph Weisberg"], "genres": ["Crime", "Drama", "Mystery", "Thriller"], "seasons_count": 6, "episodes_count": 75, "imdb_rating": 8.4, "imdb_votes": "115,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 89, "streaming_services": ["Hulu"], "top_episode": "START (S6E10 - 9.7)", "plot": "Two Soviet KGB spies pose as an ordinary American married couple living in suburban Washington D.C. with their unsuspecting children."},
    {"title": "Boardwalk Empire", "start_year": 2010, "end_year": 2014, "creators": ["Terence Winter"], "genres": ["Crime", "Drama"], "seasons_count": 5, "episodes_count": 56, "imdb_rating": 8.6, "imdb_votes": "205,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 83, "streaming_services": ["Max"], "top_episode": "To the Lost (S2E12 - 9.4)", "plot": "Nucky Thompson rules Atlantic City through political power and bootleg whiskey shipments."},
    {"title": "The Leftovers", "start_year": 2014, "end_year": 2017, "creators": ["Damon Lindelof", "Tom Perrotta"], "genres": ["Drama", "Fantasy", "Mystery"], "seasons_count": 3, "episodes_count": 28, "imdb_rating": 8.3, "imdb_votes": "110,000+", "rotten_tomatoes_pct": 91, "metacritic_score": 76, "streaming_services": ["Max"], "top_episode": "International Assassin (S2E8 - 9.7)", "plot": "Three years after 2% of the global population vanishes into thin air, survivors grapple with unfathomable grief and bizarre cults."},
    {"title": "Peep Show", "start_year": 2003, "end_year": 2015, "creators": ["Andrew O'Connor", "Jesse Armstrong", "Sam Bain"], "genres": ["Comedy"], "seasons_count": 9, "episodes_count": 54, "imdb_rating": 8.6, "imdb_votes": "65,000+", "rotten_tomatoes_pct": 96, "metacritic_score": 85, "streaming_services": ["Hulu", "BritBox"], "top_episode": "Seasonal Beatings (S7E5 - 9.3)", "plot": "Mark and Jez are two dysfunctional London flatmates viewed entirely through first-person POV cameras and inner monologues."},

    # 71 - 80
    {"title": "Doctor Who (2005)", "start_year": 2005, "end_year": 2025, "creators": ["Russell T Davies", "Steven Moffat"], "genres": ["Adventure", "Drama", "Sci-Fi"], "seasons_count": 14, "episodes_count": 180, "imdb_rating": 8.6, "imdb_votes": "240,000+", "rotten_tomatoes_pct": 90, "metacritic_score": 78, "streaming_services": ["Disney+", "Max"], "top_episode": "Blink (S3E10 - 9.8)", "plot": "The eccentric alien Time Lord travels across time and space in the TARDIS alongside human companions battling Daleks and Weeping Angels."},
    {"title": "Vikings", "start_year": 2013, "end_year": 2020, "creators": ["Michael Hirst"], "genres": ["Action", "Adventure", "Drama", "History", "War"], "seasons_count": 6, "episodes_count": 89, "imdb_rating": 8.5, "imdb_votes": "580,000+", "rotten_tomatoes_pct": 93, "metacritic_score": 74, "streaming_services": ["Netflix", "Hulu"], "top_episode": "All His Angels (S4E15 - 9.5)", "plot": "Legendary Norse hero Ragnar Lothbrok rises from humble farmer to ferocious Viking king raiding Anglo-Saxon England and France."},
    {"title": "Sons of Anarchy", "start_year": 2008, "end_year": 2014, "creators": ["Kurt Sutter"], "genres": ["Action", "Crime", "Drama", "Thriller"], "seasons_count": 7, "episodes_count": 92, "imdb_rating": 8.6, "imdb_votes": "310,000+", "rotten_tomatoes_pct": 87, "metacritic_score": 75, "streaming_services": ["Hulu"], "top_episode": "NS (S3E13 - 9.7)", "plot": "Jax Teller struggles with brotherhood, morality, and illegal gun-running inside an outlaw motorcycle club in Charming, California."},
    {"title": "The IT Crowd", "start_year": 2006, "end_year": 2013, "creators": ["Graham Linehan"], "genres": ["Comedy"], "seasons_count": 5, "episodes_count": 25, "imdb_rating": 8.5, "imdb_votes": "165,000+", "rotten_tomatoes_pct": 88, "metacritic_score": 70, "streaming_services": ["Netflix"], "top_episode": "The Work Outing (S2E1 - 9.7)", "plot": "Two socially inept computer technicians and their technologically illiterate manager handle IT requests in a dreary basement."},
    {"title": "Archer", "start_year": 2009, "end_year": 2023, "creators": ["Adam Reed"], "genres": ["Animation", "Action", "Comedy"], "seasons_count": 14, "episodes_count": 145, "imdb_rating": 8.6, "imdb_votes": "170,000+", "rotten_tomatoes_pct": 91, "metacritic_score": 79, "streaming_services": ["Hulu", "Netflix"], "top_episode": "Placebo Effect (S2E9 - 9.3)", "plot": "Suave but narcissistic secret agent Sterling Archer works for international intelligence agency ISIS run by his domineering mother."},
    {"title": "Person of Interest", "start_year": 2011, "end_year": 2016, "creators": ["Jonathan Nolan"], "genres": ["Action", "Crime", "Drama", "Sci-Fi", "Thriller"], "seasons_count": 5, "episodes_count": 103, "imdb_rating": 8.5, "imdb_votes": "200,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 70, "streaming_services": ["Prime Video"], "top_episode": "If-Then-Else (S4E11 - 9.9)", "plot": "A reclusive software billionaire builds an omniscient surveillance AI that predicts premeditated murders before they happen."},
    {"title": "Invincible", "start_year": 2021, "end_year": 2026, "creators": ["Robert Kirkman"], "genres": ["Animation", "Action", "Adventure", "Drama", "Sci-Fi"], "seasons_count": 2, "episodes_count": 16, "imdb_rating": 8.7, "imdb_votes": "230,000+", "rotten_tomatoes_pct": 99, "metacritic_score": 82, "streaming_services": ["Prime Video"], "top_episode": "Where I Really Come From (S1E8 - 9.7)", "plot": "Mark Grayson inherits superpowers from his father Omni-Man, the most powerful being on Earth, only to discover a terrifying secret."},
    {"title": "South Park", "start_year": 1997, "end_year": 2026, "creators": ["Trey Parker", "Matt Stone"], "genres": ["Animation", "Comedy"], "seasons_count": 26, "episodes_count": 325, "imdb_rating": 8.7, "imdb_votes": "400,000+", "rotten_tomatoes_pct": 80, "metacritic_score": 75, "streaming_services": ["Max", "Paramount+"], "top_episode": "Scott Tenorman Must Die (S5E4 - 9.6)", "plot": "Four foul-mouthed Colorado fourth-graders experience grotesque, hilarious, satirical adventures skewering modern society."},
    {"title": "The Simpsons (Golden Era)", "start_year": 1989, "end_year": 2026, "creators": ["Matt Groening"], "genres": ["Animation", "Comedy"], "seasons_count": 35, "episodes_count": 760, "imdb_rating": 8.7, "imdb_votes": "430,000+", "rotten_tomatoes_pct": 85, "metacritic_score": 79, "streaming_services": ["Disney+"], "top_episode": "Homer's Enemy (S8E23 - 9.3)", "plot": "The satirical misadventures of a working-class nuclear plant family in the misfit town of Springfield."},
    {"title": "Futurama", "start_year": 1999, "end_year": 2025, "creators": ["David X. Cohen", "Matt Groening"], "genres": ["Animation", "Adventure", "Comedy", "Sci-Fi"], "seasons_count": 8, "episodes_count": 150, "imdb_rating": 8.5, "imdb_votes": "260,000+", "rotten_tomatoes_pct": 86, "metacritic_score": 72, "streaming_services": ["Hulu", "Disney+"], "top_episode": "Jurassic Bark (S4E7 - 9.3)", "plot": "Pizza delivery boy Philip J. Fry is accidentally cryogenically frozen in 1999 and thaws out in the zany 31st century."},

    # 81 - 90
    {"title": "House of Cards", "start_year": 2013, "end_year": 2018, "creators": ["Beau Willimon"], "genres": ["Drama"], "seasons_count": 6, "episodes_count": 73, "imdb_rating": 8.6, "imdb_votes": "520,000+", "rotten_tomatoes_pct": 77, "metacritic_score": 73, "streaming_services": ["Netflix"], "top_episode": "Chapter 14 (S2E1 - 9.5)", "plot": "Ruthless Democratic congressman Frank Underwood plots ruthless political revenge against the politicians who betrayed him."},
    {"title": "Sherlock Holmes (1984)", "start_year": 1984, "end_year": 1994, "creators": ["John Hawkesworth"], "genres": ["Crime", "Drama", "Mystery"], "seasons_count": 7, "episodes_count": 41, "imdb_rating": 8.7, "imdb_votes": "28,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 85, "streaming_services": ["BritBox"], "top_episode": "The Devil's Foot (S3E2 - 8.8)", "plot": "Jeremy Brett masterfully portrays Sir Arthur Conan Doyle's eccentric sleuth across London fog and countryside cases."},
    {"title": "Silicon Valley", "start_year": 2014, "end_year": 2019, "creators": ["John Altschuler", "Mike Judge"], "genres": ["Comedy"], "seasons_count": 6, "episodes_count": 53, "imdb_rating": 8.5, "imdb_votes": "155,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 84, "streaming_services": ["Max"], "top_episode": "Optimal Tip-to-Tip Efficiency (S1E8 - 9.4)", "plot": "Tech engineer Richard Hendricks and his misfit startup team fight tech conglomerates to build revolutionary compression platform Pied Piper."},
    {"title": "Daredevil", "start_year": 2015, "end_year": 2018, "creators": ["Drew Goddard"], "genres": ["Action", "Crime", "Drama", "Sci-Fi", "Thriller"], "seasons_count": 3, "episodes_count": 39, "imdb_rating": 8.6, "imdb_votes": "460,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 75, "streaming_services": ["Disney+"], "top_episode": "The Devil You Know (S3E7 - 9.6)", "plot": "Blind lawyer Matt Murdock utilizes heightened senses to battle crime in Hell's Kitchen as masked vigilante Daredevil against Kingpin."},
    {"title": "Luther", "start_year": 2010, "end_year": 2019, "creators": ["Neil Cross"], "genres": ["Crime", "Drama", "Mystery", "Thriller"], "seasons_count": 5, "episodes_count": 20, "imdb_rating": 8.4, "imdb_votes": "150,000+", "rotten_tomatoes_pct": 88, "metacritic_score": 76, "streaming_services": ["Hulu", "BritBox"], "top_episode": "Episode 1.6 (S1E6 - 9.1)", "plot": "Near-genius London murder detective John Luther befriends sociopathic killer Alice Morgan to solve gruesome crimes."},
    {"title": "Gomorrah", "start_year": 2014, "end_year": 2021, "creators": ["Roberto Saviano"], "genres": ["Crime", "Drama"], "seasons_count": 5, "episodes_count": 58, "imdb_rating": 8.7, "imdb_votes": "42,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 76, "streaming_services": ["Max"], "top_episode": "Gelsomina Verde (S1E9 - 9.1)", "plot": "Ciro Di Marzio navigates ruthless gang warfare and betrayal within the Savastano Camorra clan in Naples, Italy."},
    {"title": "The Punisher", "start_year": 2017, "end_year": 2019, "creators": ["Steve Lightfoot"], "genres": ["Action", "Crime", "Drama", "Thriller"], "seasons_count": 2, "episodes_count": 26, "imdb_rating": 8.5, "imdb_votes": "250,000+", "rotten_tomatoes_pct": 64, "metacritic_score": 58, "streaming_services": ["Disney+"], "top_episode": "Memento Mori (S1E12 - 9.3)", "plot": "Former Force Recon Marine Frank Castle exacts brutal revenge on the conspirators responsible for the murder of his family."},
    {"title": "White Lotus", "start_year": 2021, "end_year": 2025, "creators": ["Mike White"], "genres": ["Comedy", "Drama"], "seasons_count": 2, "episodes_count": 13, "imdb_rating": 8.0, "imdb_votes": "220,000+", "rotten_tomatoes_pct": 92, "metacritic_score": 82, "streaming_services": ["Max"], "top_episode": "Bygones (S2E7 - 9.2)", "plot": "Social satire following the exploits of employees and wealthy guests at an exclusive luxury Hawaiian and Sicilian resort chain."},
    {"title": "Normal People", "start_year": 2020, "end_year": 2020, "creators": ["Lenny Abrahamson"], "genres": ["Drama", "Romance"], "seasons_count": 1, "episodes_count": 12, "imdb_rating": 8.4, "imdb_votes": "85,000+", "rotten_tomatoes_pct": 91, "metacritic_score": 82, "streaming_services": ["Hulu"], "top_episode": "Episode 10 (S1E10 - 9.2)", "plot": "Marianne and Connell navigate complex romance and emotional trauma across high school and Trinity College Dublin."},
    {"title": "The Good Place", "start_year": 2016, "end_year": 2020, "creators": ["Michael Schur"], "genres": ["Comedy", "Drama", "Fantasy"], "seasons_count": 4, "episodes_count": 50, "imdb_rating": 8.2, "imdb_votes": "180,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 82, "streaming_services": ["Netflix"], "top_episode": "Whenever You're Ready (S4E13 - 9.6)", "plot": "Deceased Eleanor Shellstrop wakes up in a heaven-like afterlife, only to realize she was admitted by a clerical mistake."},

    # 91 - 100
    {"title": "Garth Marenghi's Darkplace", "start_year": 2004, "end_year": 2004, "creators": ["Matthew Holness", "Richard Ayoade"], "genres": ["Comedy", "Horror", "Sci-Fi"], "seasons_count": 1, "episodes_count": 6, "imdb_rating": 8.4, "imdb_votes": "22,000+", "rotten_tomatoes_pct": 89, "metacritic_score": 80, "streaming_services": ["Channel 4", "Prime Video"], "top_episode": "Skipper the Eyechild (S1E4 - 8.8)", "plot": "Hilarious cult spoof of 1980s low-budget supernatural hospital horror series produced by pompous horror writer Garth Marenghi."},
    {"title": "Broad City", "start_year": 2014, "end_year": 2019, "creators": ["Abbi Jacobson", "Ilana Glazer"], "genres": ["Comedy"], "seasons_count": 5, "episodes_count": 50, "imdb_rating": 8.4, "imdb_votes": "52,000+", "rotten_tomatoes_pct": 99, "metacritic_score": 88, "streaming_services": ["Hulu", "Paramount+"], "top_episode": "Wisdom Teeth (S2E3 - 9.0)", "plot": "Two 20-something best friends navigate mundane and absurd adventures throughout New York City with chaotic joy."},
    {"title": "Flight of the Conchords", "start_year": 2007, "end_year": 2009, "creators": ["James Bobin", "Jemaine Clement", "Bret McKenzie"], "genres": ["Comedy", "Music"], "seasons_count": 2, "episodes_count": 22, "imdb_rating": 8.6, "imdb_votes": "65,000+", "rotten_tomatoes_pct": 94, "metacritic_score": 75, "streaming_services": ["Max"], "top_episode": "Sally Returns (S1E5 - 8.7)", "plot": "Two New Zealand folk musicians struggle with zero budget, eccentric management, and romantic flops in New York City."},
    {"title": "Brooklyn Nine-Nine", "start_year": 2013, "end_year": 2021, "creators": ["Dan Goor", "Michael Schur"], "genres": ["Comedy", "Crime"], "seasons_count": 8, "episodes_count": 153, "imdb_rating": 8.4, "imdb_votes": "360,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 73, "streaming_services": ["Peacock", "Netflix"], "top_episode": "The Box (S5E14 - 9.5)", "plot": "Talented but childish detective Jake Peralta clashes with strict Captain Raymond Holt in Brooklyn's 99th precinct."},
    {"title": "What We Do in the Shadows", "start_year": 2019, "end_year": 2024, "creators": ["Jemaine Clement"], "genres": ["Comedy", "Fantasy", "Horror"], "seasons_count": 6, "episodes_count": 60, "imdb_rating": 8.6, "imdb_votes": "95,000+", "rotten_tomatoes_pct": 97, "metacritic_score": 81, "streaming_services": ["Hulu"], "top_episode": "On the Run (S2E6 - 9.4)", "plot": "Mockumentary chronicling the nightly exploits of four vampire roommates who have lived together for centuries on Staten Island."},
    {"title": "Mind Your Language", "start_year": 1977, "end_year": 1986, "creators": ["Vince Powell"], "genres": ["Comedy"], "seasons_count": 4, "episodes_count": 42, "imdb_rating": 8.6, "imdb_votes": "18,000+", "rotten_tomatoes_pct": 82, "metacritic_score": 70, "streaming_services": ["YouTube", "Prime Video"], "top_episode": "The First Day (S1E1 - 8.9)", "plot": "Mild-mannered English teacher Jeremy Brown teaches English as a Foreign Language to a colourful class of immigrants in London."},
    {"title": "Spaced", "start_year": 1999, "end_year": 2001, "creators": ["Jessica Hynes", "Simon Pegg"], "genres": ["Action", "Comedy"], "seasons_count": 2, "episodes_count": 14, "imdb_rating": 8.5, "imdb_votes": "55,000+", "rotten_tomatoes_pct": 100, "metacritic_score": 85, "streaming_services": ["Hulu", "Channel 4"], "top_episode": "Gone (S2E5 - 9.2)", "plot": "Two strangers pretend to be a romantic couple to qualify for a London flat, surrounded by eccentric friends and pop culture parodies."},
    {"title": "The Thick of It", "start_year": 2005, "end_year": 2012, "creators": ["Armando Iannucci"], "genres": ["Comedy"], "seasons_count": 4, "episodes_count": 24, "imdb_rating": 8.7, "imdb_votes": "30,000+", "rotten_tomatoes_pct": 95, "metacritic_score": 87, "streaming_services": ["BritBox", "BBC iPlayer"], "top_episode": "Episode 4.6 (S4E6 - 9.2)", "plot": "Foul-mouthed spin doctor Malcolm Tucker terrorizes British government cabinet ministers in a vicious political satire."},
    {"title": "Luther", "start_year": 2010, "end_year": 2019, "creators": ["Neil Cross"], "genres": ["Crime", "Drama", "Mystery"], "seasons_count": 5, "episodes_count": 20, "imdb_rating": 8.4, "imdb_votes": "150,000+", "rotten_tomatoes_pct": 88, "metacritic_score": 76, "streaming_services": ["Hulu"], "top_episode": "Episode 1.6 (S1E6 - 9.1)", "plot": "John Luther navigates darkness inside London murders with obsessive brilliance alongside psychopath Alice Morgan."},
    {"title": "The X-Files", "start_year": 1993, "end_year": 2018, "creators": ["Chris Carter"], "genres": ["Crime", "Drama", "Mystery", "Sci-Fi"], "seasons_count": 11, "episodes_count": 218, "imdb_rating": 8.6, "imdb_votes": "240,000+", "rotten_tomatoes_pct": 74, "metacritic_score": 75, "streaming_services": ["Hulu", "Disney+"], "top_episode": "Bad Blood (S5E12 - 9.4)", "plot": "FBI special agents Fox Mulder and Dana Scully investigate unsolved paranormal and extraterrestrial cases."}
]

# Top Rated Series Episodes in TV History (IMDb 9.7 to 10.0)
TOP_SERIES_EPISODES: List[Dict[str, Any]] = [
    {"series_title": "Breaking Bad", "episode_title": "Ozymandias", "season": 5, "episode_number": 14, "imdb_rating": 10.0, "imdb_votes": "220,000+", "director": "Rian Johnson", "writer": "Moira Walley-Beckett", "plot": "Walt goes on the run as his life and empire collapse around him in catastrophic fashion."},
    {"series_title": "Breaking Bad", "episode_title": "Face Off", "season": 4, "episode_number": 13, "imdb_rating": 9.9, "imdb_votes": "75,000+", "director": "Vince Gilligan", "writer": "Vince Gilligan", "plot": "Walt makes his final desperate move against Gus Fring with Hector Salamanca."},
    {"series_title": "Game of Thrones", "episode_title": "Battle of the Bastards", "season": 6, "episode_number": 9, "imdb_rating": 9.9, "imdb_votes": "220,000+", "director": "Miguel Sapochnik", "writer": "David Benioff, D.B. Weiss", "plot": "Jon Snow and Sansa Stark face Ramsay Bolton in a brutal clash for Winterfell."},
    {"series_title": "Game of Thrones", "episode_title": "The Rains of Castamere", "season": 3, "episode_number": 9, "imdb_rating": 9.9, "imdb_votes": "110,000+", "director": "David Nutter", "writer": "David Benioff, D.B. Weiss", "plot": "Robb Stark and his mother Catelyn attend Edmure Tully's wedding at the Twins with catastrophic betrayal."},
    {"series_title": "Game of Thrones", "episode_title": "The Winds of Winter", "season": 6, "episode_number": 10, "imdb_rating": 9.9, "imdb_votes": "150,000+", "director": "Miguel Sapochnik", "writer": "David Benioff, D.B. Weiss", "plot": "Cersei Lannister faces her trial with wild wildfire under the Sept of Baelor."},
    {"series_title": "Succession", "episode_title": "Connor's Wedding", "season": 4, "episode_number": 3, "imdb_rating": 9.9, "imdb_votes": "52,000+", "director": "Mark Mylod", "writer": "Jesse Armstrong", "plot": "The Roy siblings confront an earth-shattering sudden tragedy while gathered for Connor's boat wedding."},
    {"series_title": "Chernobyl", "episode_title": "Vichnaya Pamyat", "season": 1, "episode_number": 5, "imdb_rating": 9.9, "imdb_votes": "65,000+", "director": "Johan Renck", "writer": "Craig Mazin", "plot": "Valery Legasov testifies at the state trial, revealing the fatal truth about Soviet nuclear reactor design flaws."},
    {"series_title": "Better Call Saul", "episode_title": "Plan and Execution", "season": 6, "episode_number": 7, "imdb_rating": 9.9, "imdb_votes": "46,000+", "director": "Thomas Schnauz", "writer": "Thomas Schnauz", "plot": "Jimmy and Kim execute their elaborate scheme against Howard Hamlin, until Lalo Salamanca arrives."},
    {"series_title": "Better Call Saul", "episode_title": "Point and Shoot", "season": 6, "episode_number": 8, "imdb_rating": 9.9, "imdb_votes": "38,000+", "director": "Vince Gilligan", "writer": "Gordon Smith", "plot": "Gus Fring confronts Lalo Salamanca in the dark depths of the secret subterranean meth lab."},
    {"series_title": "Mr. Robot", "episode_title": "407 Proxy Authentication Required", "season": 4, "episode_number": 7, "imdb_rating": 9.9, "imdb_votes": "36,000+", "director": "Sam Esmail", "writer": "Sam Esmail", "plot": "In a five-act theatrical confrontation, Vera forces Elliot and Krista to reveal Elliot's deepest childhood trauma."},
    {"series_title": "Six Feet Under", "episode_title": "Everyone's Waiting", "season": 5, "episode_number": 12, "imdb_rating": 9.9, "imdb_votes": "22,000+", "director": "Alan Ball", "writer": "Alan Ball", "plot": "Widely heralded as the greatest series finale in television history, chronicling the future passings of the Fisher family."},
    {"series_title": "BoJack Horseman", "episode_title": "The View from Halfway Down", "season": 6, "episode_number": 15, "imdb_rating": 9.9, "imdb_votes": "35,000+", "director": "Amy Winfrey", "writer": "Alison Tafel", "plot": "BoJack attends an ethereal dinner party with deceased figures from his past on the threshold of life and death."},
    {"series_title": "Dexter", "episode_title": "The Getaway", "season": 4, "episode_number": 12, "imdb_rating": 9.8, "imdb_votes": "26,000+", "director": "Steve Shill", "writer": "Wendy West, Melissa Rosenberg", "plot": "Dexter tracks down Trinity Killer Arthur Mitchell, leading to a shocking, tragic discovery at home."},
    {"series_title": "Hannibal", "episode_title": "Mizumono", "season": 2, "episode_number": 13, "imdb_rating": 9.8, "imdb_votes": "21,000+", "director": "Michael Rymer", "writer": "Bryan Fuller, Steve Lightfoot", "plot": "Hannibal prepares his escape as Will and Jack Crawford's trap springs with bloody consequences."},
    {"series_title": "Barry", "episode_title": "ronny/lily", "season": 2, "episode_number": 5, "imdb_rating": 9.8, "imdb_votes": "20,000+", "director": "Bill Hader", "writer": "Alec Berg, Bill Hader", "plot": "Barry is tasked with killing a taekwondo master, only to be relentlessly pursued by the man's feral daughter."},
    {"series_title": "House M.D.", "episode_title": "House's Head", "season": 4, "episode_number": 15, "imdb_rating": 9.8, "imdb_votes": "23,000+", "director": "Greg Yaitanes", "writer": "Peter Blake, David Foster", "plot": "Suffering from amnesia after a horrific bus crash, House desperately pieces together the identity of a dying passenger."},
    {"series_title": "Doctor Who", "episode_title": "Blink", "season": 3, "episode_number": 10, "imdb_rating": 9.8, "imdb_votes": "30,000+", "director": "Hettie Macdonald", "writer": "Steven Moffat", "plot": "Sally Sparrow investigates a derelict house and discovers terrifying quantum statues called the Weeping Angels."},
    {"series_title": "Community", "episode_title": "Remedial Chaos Theory", "season": 3, "episode_number": 4, "imdb_rating": 9.8, "imdb_votes": "25,000+", "director": "Jeff Melman", "writer": "Chris McKenna", "plot": "Rolling a single die to determine who gets pizza creates six distinct alternate branching timelines."},
    {"series_title": "The Shield", "episode_title": "Family Meeting", "season": 7, "episode_number": 13, "imdb_rating": 9.8, "imdb_votes": "12,000+", "director": "Clark Johnson", "writer": "Shawn Ryan", "plot": "Vic Mackey signs his federal immunity deal but loses his family, partner, and soul in the process."},
    {"series_title": "Person of Interest", "episode_title": "If-Then-Else", "season": 4, "episode_number": 11, "imdb_rating": 9.9, "imdb_votes": "17,000+", "director": "Chris Fisher", "writer": "Denise Thé", "plot": "Trapped in the New York Stock Exchange, the Machine simulates millions of survival scenarios to save Finch and Reese."}
]

# Generate Master Series DB with CineScore
MASTER_SERIES_DB: List[Dict[str, Any]] = []
for idx, s in enumerate(RAW_TOP_100_SERIES, 1):
    s_copy = dict(s)
    s_copy["id"] = f"series_top100_{idx:03d}"
    s_copy["rank_top100"] = idx
    s_copy["media_type"] = "tv_series"
    s_copy["cinescore"] = calculate_series_cinescore(s_copy["imdb_rating"], s_copy["rotten_tomatoes_pct"], s_copy["metacritic_score"])
    MASTER_SERIES_DB.append(s_copy)
